### PR TITLE
Jump To Content: Add menu button to examples to implement WCAG bypass blocks requirement

### PR DESCRIPTION
**Pull request by jongund**
This is an update to pull #1860 that got too out of synch with `main` branch, but still has a failing regression tests for the menu button link example.  
NOTE: The menu button link example and tests are not modified in this pull request.

Features:
* Added` jumpto.js`
* Uses color palette of the ARIA APG
* Uses `app.js` to add the appropriate reference to each example.

[preview link for index of examples](https://raw.githack.com/w3c/aria-practices/jump-to/examples/index.html)
[preview link for button example](https://raw.githack.com/w3c/aria-practices/jump-to/examples/button/button.html)
[preview link for checkbox 1 example](https://raw.githack.com/w3c/aria-practices/jump-to/examples/checkbox/checkbox-1/checkbox-1.html)

* [x] [Functional review](https://github.com/w3c/aria-practices/wiki/Pull-Request-Review-Process#functional_review) by @a11ydoer 
* [x] [Visual design review](https://github.com/w3c/aria-practices/wiki/Pull-Request-Review-Process#design_review) by @a11ydoer
* [ ] [Accessibility review](https://github.com/w3c/aria-practices/wiki/Pull-Request-Review-Process#accessibility_review) on Windows by @mcking65 
* [ ] [Accessibility review](https://github.com/w3c/aria-practices/wiki/Pull-Request-Review-Process#accessibility_review) on MacOS @mcking65 
* [x] [Accessibility review](https://github.com/w3c/aria-practices/wiki/Pull-Request-Review-Process#accessibility_review) on iOS/iPadOS by @jongund 
* [x] [Accessibility review](https://github.com/w3c/aria-practices/wiki/Pull-Request-Review-Process#accessibility_review) on Android by @a11ydoer
* [x] [Code review](https://github.com/w3c/aria-practices/wiki/Pull-Request-Review-Process#code_review) by @jesdaigle 
* [x] [Test review](https://github.com/w3c/aria-practices/wiki/Pull-Request-Review-Process#test_review) by @jesdaigle

### CODE REVIEW

**Comment by jongund** [comment]
@mcking65 
This version has the changes based on the 5/25 call:
1. Removed aria-describedby from button to the tooltip, and VoiceOver, Jaws and NVDA all announce the accesskey attribute information.
2. Update selectors for landmarks to only include first navigation landmark

**Comment by jongund** [comment]
@jesdaigle @mcking65 
I don't know why the regression test for menu button link example is failing, since it has not been modified.  It seems to be kind of a test that is replacing `href` values of the links before the test, so maybe some strange side effects I don't understand.  Is this something Jes can look into?

**Comment by jongund** [comment]
I have completed another test to see if I can identify the problem with menu button link test failing.
I basically disabled the loading of JumpTo script in `app.ja` and I get the same error for the menu button link test, so not sure what is going on with that test.

**Comment by mcking65** [comment]
@zcorpan @jesdaigle 

I merge #1921 and rebased this PR and the menu button tests are still failing. Thoughts?

**Review by mcking65 — COMMENTED** [review]
@jongund 

I love how this works on Windows with JAWS and NVDA in Chrome and Firefox. On example pages, if you know where you want to go, it is super fast. For instance, if you want to go to the keyboard section, just press the jump key and then the letter 'k' and enter. Because of the letter key navigation in the menu, it is much faster than any screen reader technique. Well, you could list headings, but that is a more difficult key press and, depending on screen reader, more steps.

Unfortunately, on MacOS with VoiceOver running, it is not as good. In Chrome, ctrl-opt-0 works if you pass the key through with ctrl-opt-tab first, which is quite awkward. But, in Safari, there is no way to get it to work that I can find.

I wonder if we should consider scripting the key to be opt-0 or alt-0 regardless of browser or operating system. Then it would work regardless of what screen reader is running. That would mean that we could never use alt+0 in an example, but I don't think that is an issue. Would it have any other downsides? Could it create other conflicts with example code?

**Comment by a11ydoer** [comment]
@jongund 
Could you kindly let me know the origianl repo of this widget? I am trying to undertand some details for this widget. For example, Is the visual user with mouse click for this "jump to" menu part of use case or not?

**Comment by a11ydoer** [comment]
@carmacleod @smhigley 
I am assigning both functional review and visual review to myself. I hope that is ok with you.

**Comment by jongund** [comment]
@mcking65 @a11ydoer 
I am open to using a scripted shortcut and the click to open is useful to everyone, but especially to voice recognition users to quickly navigate to specific parts of a page.  I am on vacation right now, so we hopefully can discuss on Tuesday

**Comment by zcorpan** [comment]
@mcking65 

> I merge #1921 and rebased this PR and the menu button tests are still failing. Thoughts?

Thanks. I'm a bit perplexed by that test. I've filed #1937 and opened a PR to comment out the test for now: #1938

**Comment by jongund** [comment]
@a11ydoer 
The original pull #1860, it is referenced in the first comment.

**Comment by a11ydoer** [comment]
Visual review - 
- more spacing underneath the skip to button 
- bigger font 
- better color contrast for "skip to"

**Comment by jongund** [comment]
@mcking65 
I have updated the example to use a scripted shortcut key:
1. For Windows and Linux: Alt+0
2. macOS: Command+0

The appropriate keyboard short cut is now part of the button label.

Mobile devices currently do not have the scripted shortcut, or do want them to?

I also investigated the keyboard focus ring issue on the target landmark or heading raised by Jemma, not sure why it shows for keyboard activation and not for mouse click o a menu item since it uses the same code to move focus.  But functionally it still scrolls to the location in the page and tab navigation starts from that point.  So if it is important maybe someone else can look into it.

**Comment by a11ydoer** [comment]
Android mobile testing- since the page is not mobile responsive, there is challenge for touch point size.

**Comment by a11ydoer** [comment]
> Android mobile testing- since the page is not mobile responsive, there is challenge for touch point size.

APG group decided on pushing this issue aside since APG redesign project is going on.

**Review by a11ydoer — APPROVED** [review]
APG will take care of 1) mouse click focus issue, 2)mobile touch due to lack of responsive design later.

**Comment by jongund** [comment]
@mcking65 
Jump To has been updated to use option+0 on macOS.

**Comment by jongund** [comment]
@mcking65 
Scripting the option+0 key for macOS may cause internationalization issues, since the the keypress for option+0 generates some character other than zero.   I account for this special character in the current script, but if someone is not using English keyboard it could generate another character may not not work for them.

**Review by mcking65 — APPROVED** [review]
Tested in chrome/windows, FF/Windows, Chrome/macOS, and Safari/macOs. Functionality with screen readers is good. The scripted key command works much better on Mac when VO is running. QuickNav has to be off, but that is a minor constraint beyond our control.

**Review by jesdaigle — APPROVED** [review]

**Comment by jongund** [comment]
@mcking65 
Is there anything else that needs to be done before this pull request is merged?

**Comment by jongund** [comment]
@mcking65 
Thank you for merging this pull request.

**Pull request merged**
