### PR TITLE
updated multithumb slider to use SVG and support mobile devices

### PR DESCRIPTION
**Pull request by jongund**
Updated multi-thumb slider example:

1. Using SVG for the slider controls to support high contrast
2. Added accessibility feature section
3. Additional mobile version using input[type=number] elements to set range
4. Updated code use the APG coding practices

[Preview multi-thumb slider](https://raw.githack.com/w3c/aria-practices/update-multithumb-slider/examples/slider/slider-multithumb.html)
[Preview multi-thumb slider with mobile support](https://raw.githack.com/w3c/aria-practices/update-multithumb-slider/examples/slider/slider-multithumb-mobile.html)

### Review checklist

* [ ] [Editorial review](https://github.com/w3c/aria-practices/wiki/Pull-Request-Review-Process#editorial_review) by @mcking65
* [ ] [Functional review](https://github.com/w3c/aria-practices/wiki/Pull-Request-Review-Process#functional_review) by @carmacleod 
* [ ] [Visual design review](https://github.com/w3c/aria-practices/wiki/Pull-Request-Review-Process#design_review) by @carmacleod 
* [x] [Accessibility review](https://github.com/w3c/aria-practices/wiki/Pull-Request-Review-Process#accessibility_review) by @charmarkk
* [ ] [Code review](https://github.com/w3c/aria-practices/wiki/Pull-Request-Review-Process#code_review) by @spectranaut
* [ ] [Test review](https://github.com/w3c/aria-practices/wiki/Pull-Request-Review-Process#test_review) by @spectranaut

### CODE REVIEW

**Comment by jongund** [comment]
@mcking65 @spectranaut @nschonni 
Here is the new branch and PR for the update to the multi-thumb slider examples.  Seems to be passing the tests in Travis now.

**Comment by charmarkk** [comment]
Tested with Windows 10, NVDA 2020.3, JAWS 2020.2012.13; Firefox 84.0.1 and Chrome 87.0.4280.141. All worked as expected as far as documented accessibility functionality, keyboard interaction, and screen readers were concerned. 

High contrast was mostly good, but the label on the thumb itself did not show up with HCM Black and Firefox. @carmacleod, could I tag you in for MacOS a11y tests? My test Mac is with another co-worker at the moment.

**Review by charmarkk — APPROVED** [review]
*disregard - mistakenly chose approve*

**Review by charmarkk — CHANGES_REQUESTED** [review]
Tested with Windows 10, NVDA 2020.3, JAWS 2020.2012.13; Firefox 84.0.1 and Chrome 87.0.4280.141. All worked as expected as far as documented accessibility functionality, keyboard interaction, and screen readers were concerned.

High contrast was mostly good, but **the label on the thumb itself did not show up with HCM Black and Firefox**. @carmacleod, could I tag you in for MacOS a11y tests? My test Mac is with another co-worker at the moment.

**Comment by jongund** [comment]
This example has been updated in Pull #1758

**Pull request closed without merging**
