### PR TITLE
Date Picker Dialog: fix aria-select  bug when using space key

### PR DESCRIPTION
**Pull request by jongund**
Fixed bug reported in issue #1446 related to updating `aria-selected` attribute when the space key is pressed, since pressing space does not close the dialog.

[Preview Link](https://raw.githack.com/w3c/aria-practices/datepicker-dialog-space-select/examples/dialog-modal/datepicker-dialog.html)

### CODE REVIEW

**Comment by mcking65** [comment]
I removed link to #1446 because this issue doesn't add the documentation that issue is about. We need that to stay open after this PR closes. Instead, I will label this a bug and put it in the datepicker project so we can track it without a related issue.

**Comment by charmarkk** [comment]
@mcking65, I think I'm following. I don't usually do things this in depth!

Win/Firefox: I do see in the accessibility tree that the name is updating to the currently selected date, but NVDA doesn't announce anything to me, and will say "not selected" even on the selected date.

Win/Chrome: I'm think I'm seeing the same as you, Matt.

I must confess, I don't know Macs well enough to that inspection. 😅 Maybe I could tap in @curtbellew or @carmacleod for that?

**Comment by carmacleod** [comment]
@mcking65 I agree with your assessment.

Win/Chrome: NVDA announces "selected" right away. JAWS doesn't announce it at all, but if you arrow away from the selected cell and then back again, JAWS will say "selected".

Win/Firefox: Confirmed that "selected" never shows up in the accessibility states for the cell. Definitely seems like a Firefox bug to me. In addition, Firefox has accessibility errors and warnings showing up in the accessibility tree viewer, bogusly complaining that "Clickable elements must be focusable and should have interactive semantics" for every date cell, even though they all have the focusable state because they all have a tabindex. So after this is merged, I'll open a couple of Firefox issues.

Mac/Chrome: Confirmed that selected is never reported by VoiceOver. I can see in the [MacOSX Accessibility Inspector that comes with XCode](https://developer.apple.com/library/archive/documentation/Accessibility/Conceptual/AccessibilityMacOSX/OSXAXTestingApps.html) that Selected is in fact true, so my best guess is that VO is not looking for the selected state on a cell.

Note that I can't for the life of me figure out how to browse the contents of the Accessibility Inspector with a keyboard. Is it possible that this Inspector doesn't support keyboard?? I can use Control-Option-Command-F5 to move the mouse cursor to the focused item (for example, the date cell), and then Option-Space to freeze/unfreeze the display of the item under the mouse in the Inspector (don't use Command-F7 - the doc clearly needs updating). However that's as far as the keyboard will take me.

Mac/Safari: Not only is the selected cell announced as a group, but there also seems to be a caching problem, where even if you move the selection to another cell, the old selected cell is still announced as group. This is very likely a webkit bug. I'll open a bug for webkit after we merge.

**Comment by carmacleod** [comment]
Looking at Core-AAM, it seems that Mac doesn't have a way to distinguish between [cell](https://www.w3.org/TR/core-aam/#role-map-cell) and [gridcell](https://www.w3.org/TR/core-aam/#role-map-gridcell)?

Both roles map to:

AXRole: AXCell
AXSubrole: `<nil>`
AXRoleDescription: 'cell'

Also, their parent roles [table](https://www.w3.org/TR/core-aam/#role-map-table) and [grid](https://www.w3.org/TR/core-aam/#role-map-grid) both map to:

AXRole: AXTable
AXSubrole: `<nil>`
AXRoleDescription: 'table'

So I'm not sure how OSX or VoiceOver is supposed to tell the difference?
It does make a difference in this case, because `cell` role supports `aria-selected`, but `gridcell` does not.

**Comment by carmacleod** [comment]
I found a few keyboard commands in the Accessibility Inspector menubar's Inspect menu. You can use Control-Command-right/left arrow to inspect the next/previous sibling element, or Control-Command-up/down arrow to inspect a parent/child element. Those used to be buttons in the Inspector's UI. I wondered where they went! However, VoiceOver still won't read the content that the Inspector is displaying.

**Comment by mcking65** [comment]
I raised #1507 to track progress on raising related browser and ARIA issues, and took the liberty of assigning @carmacleod  to it. I will go ahead and merge.

**Pull request merged**
