### PR TITLE
Checkbox Example: Restore focus styling, add accessibility features documentation, and implement current code guide practices

### PR DESCRIPTION
**Pull request by jongund**
I was looking at the checkbox example and I noticed that at some point the accessibility features related to visual focus styling had been removed.  I have have updated the example and also added accessibility documentation on the visual focus and hover styling improvements for accessibility.

[Preview Link](https://raw.githack.com/w3c/aria-practices/update-checkbox/examples/checkbox/checkbox.html)

Changes:
* Renamed example HTML file: `checkbox.html` (NOTE: the mixed checkbox example will use the `checkbox-mixed.html` file name).
* Updated JS code to use current coding practices.
* Changed from using `event.keyCode` to `event.key` in event handlers.
* Restored visual focus styling features that were removed from the example.
* Added documentation of accessibility features.

### Review checklist

* [ ] [Editorial review](https://github.com/w3c/aria-practices/wiki/Pull-Request-Review-Process#editorial_review) by @mcking65
* [ ] [Visual design review](https://github.com/w3c/aria-practices/wiki/Pull-Request-Review-Process#design_review) by @charmarkk 
* [x] [Accessibility review](https://github.com/w3c/aria-practices/wiki/Pull-Request-Review-Process#accessibility_review) on Windows by @charmarkk
* [ ] [Accessibility review](https://github.com/w3c/aria-practices/wiki/Pull-Request-Review-Process#accessibility_review) on MacOS by @charmarkk  
* [x] [Accessibility review](https://github.com/w3c/aria-practices/wiki/Pull-Request-Review-Process#accessibility_review) on iOS/iPadOS by @jongund 
* [x] [Code review](https://github.com/w3c/aria-practices/wiki/Pull-Request-Review-Process#code_review) by @zcorpan 
* [x] [Test review](https://github.com/w3c/aria-practices/wiki/Pull-Request-Review-Process#test_review) by @zcorpan

### CODE REVIEW

**Comment by jongund** [comment]
@nschonni 
I do not understand the linting error I am getting now.  
Something to do with  "npm install dependencies", how do I fix this?

**Comment by nschonni** [comment]
Looks like a random hiccup to me in the general install step. I'd suggest trying to restart the job if you have permission

**Review by charmarkk — APPROVED** [review]
Looks good with Firefox/Chrome and NVDA/JAWS latest. HCM Black and White looks good!

**Review by zcorpan — APPROVED** [review]
Code review and test review done, looks good to me.

**Comment by zcorpan** [comment]
Rebased and resolved merge conflicts in `examples/index.html` by running `npm run reference-tables`

**Review by jesdaigle — APPROVED** [review]

**Pull request merged**
