### PR TITLE
Switch Example using Button: Fix white on white bug 

### PR DESCRIPTION
**Pull request by jongund**
___
[WAI Preview Link](https://deploy-preview-160--wai-aria-practices2.netlify.app)
[Preview of Switch using Button Example](https://deploy-preview-160--wai-aria-practices2.netlify.app/aria/apg/example-index/switch/switch-button.html)

### CODE REVIEW

**Review by jnurthen — APPROVED** [review]
LGTM

**Review by alflennik — APPROVED** [review]
Fixed!

**Comment by mcking65** [comment]
@s3ththompson 

This commit is ready to be added to the publication branch.

Note that @a11ydoer is working on another PR that we'd also like to include in publication this week if we can get it ready in time. She is still drafting.

**Comment by mcking65** [comment]
Thank you @jongund for the fix!!

**Comment by a11ydoer** [comment]
@s3ththompson @mcking65 @alflennik 
I forgot to create the branch and committed the change directly to main branch....do you want me to create the branch and create PR?

**Comment by alflennik** [comment]
These changes have been incorporated to the move-examples branch so they won't be lost when it goes live.

**Pull request merged**
