### PR TITLE
Jump To Content: Add menu button to examples to implement WCAG bypass blocks requirement

### PR DESCRIPTION
**Pull request by jongund**
Features:
* Added` jumpto.js`
* Uses color palette of the ARIA APG
* Uses `app.js` to add the appropriate reference to each example.

[preview link for index of examples](https://raw.githack.com/w3c/aria-practices/add-jump-to/examples/index.html)
[preview link for button example](https://raw.githack.com/w3c/aria-practices/add-jump-to/examples/button/button.html)
[preview link for checkbox 1 example](https://raw.githack.com/w3c/aria-practices/add-jump-to/examples/checkbox/checkbox-1/checkbox-1.html)

* [ ] [Functional review](https://github.com/w3c/aria-practices/wiki/Pull-Request-Review-Process#functional_review) by @carmacleod 
* [ ] [Visual design review](https://github.com/w3c/aria-practices/wiki/Pull-Request-Review-Process#design_review) by @smhigley 
* [ ] [Accessibility review](https://github.com/w3c/aria-practices/wiki/Pull-Request-Review-Process#accessibility_review) on Windows by [TBD]
* [ ] [Accessibility review](https://github.com/w3c/aria-practices/wiki/Pull-Request-Review-Process#accessibility_review) on MacOS by @carmacleod 
* [ ] [Accessibility review](https://github.com/w3c/aria-practices/wiki/Pull-Request-Review-Process#accessibility_review) on iOS/iPadOS by @jongund 
* [ ] [Accessibility review](https://github.com/w3c/aria-practices/wiki/Pull-Request-Review-Process#accessibility_review) on Android by @a11ydoer
* [ ] [Code review](https://github.com/w3c/aria-practices/wiki/Pull-Request-Review-Process#code_review) by @jesdaigle 
* [ ] [Test review](https://github.com/w3c/aria-practices/wiki/Pull-Request-Review-Process#test_review) by @jesdaigle

### CODE REVIEW

**Comment by jongund** [comment]
@mcking65 
What is the status of this pull request?

**Comment by shirsha** [comment]
Thanks @jongund  for these examples.
Here are my observations:

- The visual focus indicator is cutoff at the top.
- Can we use "Go to Content" or "Skip to Content "  instead of "Jump to content"?
- The navigation landmarks are missing explicit labels ( for index example)
- The navigation landmark is missing label ( for checkbox 1 and button example)
- The tooltip is not dismissible via [Escape] key. It violates the content on hover/focus WCAG:1.4.13 criteria. 
Tooltips are not supported on mobile as touch events don't throw the focus event. The VO/iOS doesn't narrate the tooltip. 
On desktop, tooltips are not dismissed in browse/ read mode.

- For usability suggest to provide a arrow for the tooltip so clarify which element has the tooltip.
- More discussion on tooltip is at  https://github.com/w3c/aria-practices/issues/128

image


image

**Comment by mcking65** [comment]
@shirsha, thank you for the feedback!!

> * Can we use "Go to Content" or "Skip to Content "  instead of "Jump to content"?

We changed the code module name from "skipto" to "jumpto" to be sure there was no copyright confusion. While we changed the name of the plugin, I guess we don't necessarily have to change the words in the UI. "Skip to" is OK. "Go to" could be thought of as going to another page; we should avoid that.

Nevertheless, since the module is called "jumpto", it does seem better to use the words "jump to". What is the reason for not using "jump to"?

> * The navigation landmarks are missing explicit labels ( for index example)
> * The navigation landmark is missing label ( for checkbox 1 and button example)

Lost here ... can you please point to the pages where these things are missing?

**Comment by jongund** [comment]
@nschonni 
@mcking65 
The push process is broken somehow again:
1. Getting this error when trying to push from my local machine to the repository: `.husky/pre-commit: line 2: .husky/_/husky.sh: No such file or directory`
2. Regression tests for files un-related to the files I change failing 
3. Trying to just edit files using git hub errors leads to HTML linking errors

Very frustrating when I can't even push simple one or two line changes to a existing branch that was already passing all the tests.

I tried re-running the tests, it did not fix the failing test.

What should I do next?

**Comment by jongund** [comment]
@shirsha 
I updated the "Jump To" to:
1. Use the escape key to hide the tooltip
2. Border on top now appears for focus and hover.
3. I don't think we need any pointer for this tooltip, it is pretty short tooltip and it appears close to the button on focus or hover, and there is nothing else near it. 
4. I think "Jump To" is fine, but if the group wants "Skip To" that is fine with me too, not strong opinion on the issue.

This pull request will not be addressing the issue of landmarks that do not have accessible names in individual examples. I suggest opening that question up as an issue for the group to discuss what to do about it.

**Comment by shirsha** [comment]
Thanks @jongund for the updates.
I felt "Jump to" might look like a ablest word.  Her we are replacing skip to main to skip to content with more options.
Tooltip is not supported on mobile,  we should reconsider the usage of tooltip.
For landmarks I will raise a new issue in the GitHub.

**Comment by jongund** [comment]
@shirsha 
We do not need the tooltip on mobile, because at least in my testing accesskeys don't work on mobile browsers.

**Comment by jongund** [comment]
@mcking65 
For some reason this branch is failing the menu-button link test for the ENTER key, even though none of the menu button example files were touches in this pull request.

**Comment by mcking65** [comment]
@shirsha 

I'm pretty sure that if "jump to" were considered ablest, then  "skip to" would be equally or even more so.

**Comment by a11ydoer** [comment]
@jongund 

We will talk about this at APG meeting on [May 25, 2021](https://github.com/w3c/aria-practices/wiki/May-25,-2021-Agenda). I also assigned reviewers.

**Comment by jongund** [comment]
Update code:
* removed `aria-describedby` from button for tooltip
* Updated landmark selector to only get first navigation landmark region

**Comment by jongund** [comment]
This pull request has been moved to pull #1923.

**Pull request closed without merging**
