### PR TITLE
chore: Ignore data svgs for spellcheck

### PR DESCRIPTION
**Pull request by nschonni**

### CODE REVIEW

**Comment by nschonni** [comment]
@spectranaut @jongund figured this might be easier for the migration of the SVGs instead of one-off dictionary words for the url encoded words

**Review by spectranaut — APPROVED** [review]
perfect :)

**Review by carmacleod — APPROVED** [review]
Nice!
Good idea, @nschonni !

**Review by mcking65 — APPROVED** [review]
Nice! Thank you @nschonni

**Pull request merged**
