### PR TITLE
Menu and Menubar Pattern: Clarify Tab key behavior

### PR DESCRIPTION
**Pull request by jongund**
Resolves issue #2044 
Updated description in `menubar` pattern to clarify use of tab and shift + tab.

***

### :boom: Error: 504 Gateway Timeout :boom: ###

[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on May 10, 2022, 3:27 PM UTC)_.

<details>
<summary>More</summary>

PR Preview relies on a number of web services to run. There seems to be an issue with the following one:

:rotating_light: [Spec Generator](https://www.w3.org/2015/labs/) - Spec Generator is the web service used to build specs that rely on ReSpec.

:link: [Related URL](https://labs.w3.org/spec-generator/?type=respec&url=https%3A%2F%2Fraw.githubusercontent.com%2Fw3c%2Faria-practices%2F072f18be121623bf95f35294cf8657f213b38186%2Faria-practices.html%3FisPreview%3Dtrue)

```
<html><body><h1>504 Gateway Time-out</h1>
The server didn't respond in time.
</body></html>

```

_If you don't have enough information above to solve the error by yourself (or to understand to which web service the error is related to, if any), please [file an issue](https://github.com/tobie/pr-preview/issues/new?title=Error%20not%20surfaced%20properly&body=See%20w3c/aria-practices%232266.)._
</details>

### CODE REVIEW

**Comment by howard-e** [comment]
@jongund rebasing on `main` to get the updated `index.html` should solve the `lint-html` build error you're having here.

**Comment by jongund** [comment]
> @jongund rebasing on `main` to get the updated `index.html` should solve the `lint-html` build error you're having here.

@howard-e I just checkout this branch and when I do a rebase this the result I get:

```
jongunderson@DRES-JONGUND-2018MacMini aria-practices % git branch
  main
* menubar-pattern-tab-desc
jongunderson@DRES-JONGUND-2018MacMini aria-practices % git rebase main
Current branch menubar-pattern-tab-desc is up to date.
```

**Comment by howard-e** [comment]
> @howard-e I just checkout this branch out from main a few hours ago and when I do a rebase this the result I get:

@jongund seems the updated `index.html` went in shortly after this PR was submitted. Could you try:
```bash
git fetch origin main
git rebase main
git push --force
```

My result was:
```bash
❯ gh pr checkout 2266
Branch 'menubar-pattern-tab-desc' set up to track remote branch 'menubar-pattern-tab-desc' from 'origin'.
Switched to a new branch 'menubar-pattern-tab-desc'
❯ git rebase main
Successfully rebased and updated refs/heads/menubar-pattern-tab-desc.
```

**Comment by jongund** [comment]
@howard-e 
Look good now, thank you for your help.

**Review by jnurthen — APPROVED** [review]
LGTM

**Review by jongund — COMMENTED** [review]
LGTM

**Comment by mcking65** [comment]
@jongund wrote:
> LGTM

Jon, you were a little too quick on the draw for me. I was diverted momentarily, and just finished up. I made a few more changes to make it especially clear that Tab does not move focus inside menus.

**Review by mcking65 — APPROVED** [review]

**Pull request merged**
