### PR TITLE
Toolbar Example: Add missing descriptive tooltips #986 fix

### PR DESCRIPTION
**Pull request by ardnahcivar**
added the descriptive title for the toolbar buttons.

### CODE REVIEW

**Comment by mcking65** [comment]
I'll get a reviewer assigned today. Question about changes starting at line 213, are they white space changes only? The replacement line sounds the same as the original to me.

**Comment by ardnahcivar** [comment]
> I'll get a reviewer assigned today. Question about changes starting at line 213, are they white space changes only? The replacement line sounds the same as the original to me.

yes at line 213 onwards,  it is white space changes only

**Comment by jongund** [comment]
@ardnahcivar @mcking65 
I don't think we want to do it this way, it you want the tooltips with the title attribute we need to remove aria-label, otherwise we are setting up a situation where the accessible name will be the same as the accessible description.  This also needs to be documented in the example descriptions for use of  properties and states.

**Comment by ardnahcivar** [comment]
> @ardnahcivar @mcking65
> I don't think we want to do it this way, it you want the tooltips with the title attribute we need to remove aria-label, otherwise we are setting up a situation where the accessible name will be the same as the accessible description. This also needs to be documented in the example descriptions for use of properties and states.

@jongund , any pointers, sugesstions  how to fix it

**Comment by carmacleod** [comment]
Hi, @ardnahcivar! Thank-you so much for your pull request!

The group discussed this yesterday, and we decided that we prefer not to use the `title` attribute because sighted keyboard users cannot see browser tooltips, so `title` is not the best choice for accessible tooltips.

The W3C HTML spec for the [title attribute](http://w3c.github.io/html/dom.html#the-title-attribute) mentions this:
> **Warning!** Relying on the title attribute is currently discouraged as many user agents do not expose the attribute in an accessible manner as required by this specification (e.g., requiring a pointing device, such as a mouse, to cause a tooltip to appear excludes keyboard-only users and touch-only users, such as anyone with a modern phone or tablet).

We believe the direction should be similar to @ZoeBijl's [example tooltip with aria-labelledby](https://github.com/w3c/aria-practices/issues/127#issuecomment-467152945) (in CodePen).

Do you want to have a go at writing this for the toolbar example?

**Comment by jongund** [comment]
@mcking65 Is this pull request going to be merged soon?

**Comment by mcking65** [comment]
@ardnahcivar, sorry we chose another path, which @jongund implemented in #1069. Closing this PR.

If you are available for other bugs, please comment in the relevant issue so we can talk about the approach to resolution. We don't want people to get discouraged from contributing because of situations like this where they offer some work and then we re-do it or go down another path.

**Pull request closed without merging**
