### PR TITLE
Spinbutton - Initial commit, work in progress

### PR DESCRIPTION
**Pull request by gerardkcohen**
This is the initial commit for the Spinbutton issue #125, very much a work in progress.

Testing without AT (VoiceOver/ Safari), UP/DOWN will increment/ decrement as designed. With AT, VoiceOver suggests different keys for operation. I am looking for advice on how to proceed.

With VO, CTRL+OPTION+UP/DOWN is required to increment/ decrement the counter. CTRL+OPTION is not firing, so while VO is announcing the change I am not capturing any events to respond to.

cc: @mcking65

### CODE REVIEW

**Comment by mcking65** [comment]
@gerardkcohen,

I'd like to develop this in a feature branch before landing in master. I made branch issue125. Could you please close this and resubmit with issue125 as the base rather than master?

Also, please run npm test. There's an eslint error.

WRT the VO slider keys, it is a bug in VO that it provides that keyboard help for a web slider. Those keys only work on native sliders. Without AOM, it is not possible for us to capture VO slider increment and decrement events in JavaScript.

**Comment by gerardkcohen** [comment]
@mcking65 In a bit of a bad cycle here. I am getting the error "Element input is missing one or more of the following attributes: type." when trying validate HTML.

Ok, add `type="text"` and get "Bad value spinbutton for attribute role on element input." with "Attribute aria-valuemin not allowed on element input at this point."

I can use `type="number"` and get off with a warning of "The spinbutton role is unnecessary for element input whose type is number." but then example changes with the native browser spinbutton UI.

This seems like a validator issue. @stevefaulkner, any comments?

**Comment by mcking65** [comment]
Raised w3c/aria-html#111.

**Comment by stevefaulkner** [comment]
@gerardkcohen will review and update where necessary

**Comment by gerardkcohen** [comment]
@stevefaulkner Thanks for the quick turnaround. Since the default type for input is `text` would omitting the type also pass?

**Comment by stevefaulkner** [comment]
@gerardkcohen WFM

**Pull request merged**
