### PR TITLE
Switch Role: Example using the DIV element

### PR DESCRIPTION
**Pull request by jongund**
[Preview link](https://raw.githack.com/w3c/aria-practices/switch/examples/switch/switch.html)

* [x] [Editorial review](https://github.com/w3c/aria-practices/wiki/Pull-Request-Review-Process#editorial_review) by @mcking65
* [x] [Functional review](https://github.com/w3c/aria-practices/wiki/Pull-Request-Review-Process#functional_review) by @carmacleod 
* [x] [Visual design review](https://github.com/w3c/aria-practices/wiki/Pull-Request-Review-Process#design_review) by @a11ydoer
* [x] [Accessibility review](https://github.com/w3c/aria-practices/wiki/Pull-Request-Review-Process#accessibility_review) on Windows by @a11ydoer   
* [x] [Accessibility review](https://github.com/w3c/aria-practices/wiki/Pull-Request-Review-Process#accessibility_review) on iOS/iPadOS by @jongund 
* [x] [Accessibility review](https://github.com/w3c/aria-practices/wiki/Pull-Request-Review-Process#accessibility_review) on Android by @a11ydoer
* [x] [Code review](https://github.com/w3c/aria-practices/wiki/Pull-Request-Review-Process#code_review) by @jesdaigle 
* [x] [Test review](https://github.com/w3c/aria-practices/wiki/Pull-Request-Review-Process#test_review) by @jesdaigle

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/aria-practices/pull/1892.html" title="Last updated on Oct 4, 2021, 4:23 PM UTC (2a5ad2f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/aria-practices/1892/a5c056f...2a5ad2f.html" title="Last updated on Oct 4, 2021, 4:23 PM UTC (2a5ad2f)">Diff</a>

### CODE REVIEW

**Comment by jongund** [comment]
@mcking65 
Made updates to:
1. Move on/off labels from CSS to content, may need `aria-hidden`.
2. Added no selection, so text is selected when activating with a mouse.

**Review by jesdaigle — APPROVED** [review]

**Comment by a11ydoer** [comment]
- check with NVDA - works well
- check with high contrast mode - dark and white theme - works well.

**Comment by jongund** [comment]
@a11ydoer @mcking65 
* High contrast support has been fixed.
* Added `aria-hidden` to on and off labels
* Updated documentation to follow switch chackbox example

**Comment by a11ydoer** [comment]
@jongund sorry for delayed review. I tested with android in Google phone. 

The switch works well with double tap in turning on and off. One problem is the responsive view in mobile phone - switch looks too small so I had to zoom in. However, this will be resolved when APG redesign project is completed. Thanks for all your work!

**Review by a11ydoer — APPROVED** [review]

**Comment by mcking65** [comment]
@jongund 
Since we already have grouping in the other two examples of switch, it seems unnecessary in this one. It is helpful to have a really basic example, especially for the aria-at project.

Would you be OK with reducing this to a single switch labeled "Notifications"?

I've finished all other editorial revisions/review on this one. I'll complete the review process after we decide about grouping.

**Comment by jongund** [comment]
@mcking65 
I updated the example to have just a single "notification" switch.

**Review by mcking65 — APPROVED** [review]
Editorial review complete. Looks awesome, thank you @jongund !

**Pull request merged**
