### PR TITLE
fix: Use GH_TOKEN token for protected branch

### PR DESCRIPTION
**Pull request by nschonni**
Allow continuing to use GitHub Secret as token for protected branch.

### CODE REVIEW

**Comment by nschonni** [comment]
@mcking65 or @michael-n-cooper with this, the GitHub actions push should still work to the protected branches here if you set a `GH_TOKEN` GitHub secret for this repo https://docs.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets

For the forks, it falls back to the regular built-in token if they haven't set the variable, or protected the `gh-pages` branch.

**Comment by mcking65** [comment]
I will need @michael-n-cooper to do this; it requires a repo owner.

**Comment by michael-n-cooper** [comment]
I've created the GH_TOKEN secret.

**Comment by nschonni** [comment]
Thanks @michael-n-cooper!
If you land this one @mcking65 we should be able to see if it's up and running again

**Comment by nschonni** [comment]
@michael-n-cooper sorry, I think the token might be wrong. 

Can you try doing this to update the GH_TOKEN value:
1. Go to https://github.com/settings/tokens/new
1. Select ` public_repo` as the only scope
1. Update https://github.com/w3c/aria-practices/settings/secrets/GH_TOKEN
1. Try to re-run the current failed job https://github.com/w3c/aria-practices/actions/runs/225990346

screen shot of selected public_repo scope

**Comment by michael-n-cooper** [comment]
Sorry, I misunderstood what should be the secret. I gave it a random value. I updated it to be the value of the GH_TOKEN for the repository, and it appeared the job succeeded.

**Comment by nschonni** [comment]
Awesome, thanks for the patience @michael-n-cooper, and sorry for the missing instructions at the start

**Comment by mcking65** [comment]
Thank you @nschonni  and @michael-n-cooper!!

**Pull request merged**
