### PR TITLE
Tablist Examples: Improve support for magnification

### LINKED ISSUE #2284: Do the ARIA TABS 1.2 fail WCAG 1.4.10 Reflow?
When using the zoom instructions from the Understanding Success Criterion [1.4.10: Reflow](https://www.w3.org/WAI/WCAG21/Understanding/reflow.html) setting a screen width of 1280px @400% browser zoom the Tabpanel content is truncated and horizontal scrolling occurs.

My personal testing demonstrates that the Tabs do reflow or stack, however the Tabpanel content does not reflow.

ALT=ARIA Tabs example zoomed and content is cut off.
Tabs-Only-zoomed

ALT=Showing Chrome Developer tools where I have removed all other page content so that only the Tab widget is available.
Tabs-Only-Code

### PR DESCRIPTION
**Pull request by jongund**
Resolves #2284 and #2257 with the following changes: 
1. Changes CSS so it defines tab width as a percentage of screen width. This prevents screen magnification from causing horizontal scrolling. As the screen is magnified ,the height of the tabs increases and the tab content reflows to fit the new dimensions.
2. Adds explanation of the use of percentage to the Accessibility Features section.

## Preview Updated Tablist Examples

* [Tablist with Automatic Activation](https://deploy-preview-201--aria-practices.netlify.app/aria/apg/patterns/tabs/examples/tabs-automatic/)
* [Tablist with Manual Activation](https://deploy-preview-201--aria-practices.netlify.app/aria/apg/patterns/tabs/examples/tabs-manual/)

### Review checklist

* [x] [Editorial review](https://github.com/w3c/aria-practices/wiki/Pull-Request-Review-Process#editorial_review) by @mcking65
* [x] [Visual design review](https://github.com/w3c/aria-practices/wiki/Pull-Request-Review-Process#design_review) by @andreancardona 
* [x] [Accessibility review](https://github.com/w3c/aria-practices/wiki/Pull-Request-Review-Process#accessibility_review) by @andreancardona 
* [x] [Code review](https://github.com/w3c/aria-practices/wiki/Pull-Request-Review-Process#code_review) by @alflennik 

___
[WAI Preview Link](https://deploy-preview-201--aria-practices.netlify.app/ARIA/apg) _(Last built on Mon, 10 Apr 2023 06:55:59 GMT)._

### CODE REVIEW

**Comment by jongund** [comment]
@mcking65 
There are many failing test in unchanged example files, the error message always seems to be "Timed out while waiting for WebDriver server".  
Not sure what to do to fix this regression testing problem.

**Comment by jongund** [comment]
@mcking65 
Same problem with the updates to the Listbox examples, failing regression tests of unchanged example files.  
Seems to be the same error message: 'Timed out while waiting for WebDriver server"

**Comment by howard-e** [comment]
> There are many failing test in unchanged example files, the error message always seems to be "Timed out while waiting for WebDriver server". Not sure what to do to fix this regression testing problem.

@jongund @mcking65 tracking in #2636 and filed a fix in #2640.

**Comment by mcking65** [comment]
@jongund

Does #2257 fit within the scope of this PR? If it would expand scope significantly, let's not include a fix for it, but if it is related to the code you are changing and simple, it might be a good issue to resolve at the same time.

**Comment by jongund** [comment]
@mcking65 
I believe the high contrast issue is also fixed for the button elements used as tabs, I will check it out before tomorrows meeting.

**Comment by jongund** [comment]
@mcking65 
I checked out the updated tablist example in high contrast and it passes our high contrast tests.  So the high contrast issue can also be closed with this pull request.

**Review by alflennik — APPROVED** [review]
The code looks good, and I confirmed that it works by comparing the current version with the updated version - for both examples I verified that the current version is causing horizontal scrollbars and that the updated version fixes the issue.

**Review by mcking65 — APPROVED** [review]
Editorial review complete; looks good.

**Comment by andreancardona** [comment]
Other than a few typos - a11 check as been done and approved!

**Comment by andreancardona** [comment]
@alflennik are the above changes something I can commit or should someone else? Other than those fixes, I'd like to approve. thank you! :)

**Comment by alflennik** [comment]
@andreancardona oh good question, I'm not sure, I've seen different kinds of approaches in past APG PRs - I've seen Matt commit editorial changes directly to PRs in the past, but I've also seen the person who opened the PR being responsible for making recommended changes. @jongund I'm curious whether you prefer for Andrea to commit spelling changes directly to the PR or for you to be responsible for that.

**Comment by mcking65** [comment]
@andreancardona wrote:

> @alflennik are the above changes something I can commit or should someone else? Other than those fixes, I'd like to approve. thank you! :)

If fixing an obvious typo, feel free to either commit or use the suggestion feature as you did.

If changing wording, please use the suggestion feature.

Thank you very very much for the thorough and detailed review!!

**Pull request merged**
