### PR TITLE
Pill list grid example: increase border and button color contrast for remove buttons

### PR DESCRIPTION
**Pull request by hellofanny**
This PR attempts to fix issue #1568 

image

I had increased the blue color to `#3a69b6`, I used the [Contrast Checker]( https://webaim.org/resources/contrastchecker/) to check it. 👍

### CODE REVIEW

**Comment by carmacleod** [comment]
@hellofanny Thanks for the PR! 
Please ignore the comment about missing tests - we are in the process of automating our build pipeline, and we will be [adding the missing tests](https://github.com/w3c/aria-practices/pull/1424) shortly.

**Review by carmacleod — APPROVED** [review]
+1

Looks good! Thanks for the contribution!

**Comment by hellofanny** [comment]
> +1
> 
> Looks good! Thanks for the contribution!

I've been studying more about web Accessibility lately and I hope to contribute more in the future ✨ Thank you for keeping this site alive!

**Comment by mcking65** [comment]
@hellofanny  thank you for the fix! @carmacleod thank you for the review. Merging!!

**Pull request merged**
