### PR TITLE
Issue #158 Add Optional Keyboard Commands to Accordion Example

### PR DESCRIPTION
**Pull request by gerardkcohen**
**For Initial Review**

This is a first attempt to contribute to this project, so this is initially for (code) review and process analysis/ exploration. There is a functional contribution here as well.

Added the following (optional) keyboard commands based on issue #158:

Up/ Down: Cycle focus through accordion toggle controls/ headings
Home/ End: Focus first/ last accordion toggle control/ heading
Control + Page Up/ Down: Move focus from accordion panel to accordion heading, and then cycle through headings.

Additionally, the accordion toggles were changed from anchors with `role="button` to native `<button>`'s. This required some minor updates to the CSS.

Lastly, there was an issue with the `forEach` helper method when iterating over objects that included inherited prototype members instead of only instance. I encountered a few bugs due to this.

### CODE REVIEW

**Comment by MichielBijl** [comment]
Thank you for your contribution @gerardkcohen, much appreciated. We’ll review this soon™.

**Comment by gerardkcohen** [comment]
@mcking65 Apologies for the delay. Unless you would object, I would like to rewrite/ refactor a lot of the JS, mainly to simplify and remove the need for the helper.js dependency.

**Comment by mcking65** [comment]
@gerardkcohen, no objections to simplifying as long as we keep the flexibility Bryan built into the code. He made it possible to configure the accordion behaviors, e.g., whether all panels can be collapsed.

However, since this has aged a bit and since I pushed some commits to your fork, this PR is going to be messy to review. So, I recommend you first rebase your commits and my commits to your 158-accordion-optional-keysbranch on to the latest master.

To get my commits to your clone, please:
git checkout 158-accordion-optional-keys
ggit pull

Then update your fork from w3c/master. Assuming you have a remote named w3c:

git fetch -p w3c
git checkout master
git merge w3c/master
git push

Then rebase:
git checkout 158-accordion-optional-keys
git rebase w3c/master

**Comment by gerardkcohen** [comment]
@mcking65 I made the change requested and followed the nice instructions you provided, but I think something happened... this PR looks a mess, which I think you predicted. Maybe we close this PR and I start over?

**Comment by gerardkcohen** [comment]
Closing in favor of #397

**Pull request closed without merging**
