### PR TITLE
Fix 2 spelling errors caught by CSpell during travis build

### PR DESCRIPTION
**Pull request by carmacleod**
- controled -> controlled
- enableing -> enabling

This little PR was created without a fork. Just making sure everything works ok. :)

This fixes the [failing build](https://travis-ci.com/github/carmacleod/aria-practices/jobs/361077898) for [PR #1432 Select-only Combobox Example: Add Accessibility Features section](https://github.com/w3c/aria-practices/pull/1432).

Not sure why CSpell didn't catch these before [PR #1413](https://github.com/w3c/aria-practices/pull/1413) was merged? Almost looks like Travis didn't run CSpell that day?

### CODE REVIEW

**Comment by nschonni** [comment]
It looks like it did catch it https://github.com/w3c/aria-practices/pull/1413/checks
When I PR'd the CSpell stuff, it was recommended that it didn't fail the job

**Comment by carmacleod** [comment]
Thanks, @nschonni - makes sense.
So I guess I'm confused about why this later build for #1432 failed: https://travis-ci.com/github/carmacleod/aria-practices/jobs/361077898

**Comment by nschonni** [comment]
The sub-job failed, but the overall build is marked as passed, since the spellcheck (and regressions) have the `ALLOW_FAILURE=true`
If you folks decide that the spellcheck is stable enough, you can delete https://github.com/w3c/aria-practices/blob/f482257ce5269f444ae74489252f03ba30fc53f9/.travis.yml#L31 and then the overall job will fail if that sub-job does

**Comment by carmacleod** [comment]
Thanks again @nschonni. I'll ask the others if they're comfortable failing builds for spelling errors. :)

Forgive my inexperience with Travis here, but I'm not sure how to tell that the [overall build](https://travis-ci.com/github/carmacleod/aria-practices/jobs/361077898) was marked as passed?

I see that the Test stage finished with 2 red X's out of 6 sub-jobs, and the fine print says those 2 are allowed to fail so Travis continued to the next stage. But the Deploy stage has red text and a red exclamation mark, and says "failed to deploy" in its log, so it seems that that stage failed?

How can a build with a big red exclamation mark and red text with the word "errored" and a failed Deploy stage be interpreted as "passed"?

I would've expected green text and a green checkmark and the word "passed", or at least yellow with an exclamation mark because the spellcheck and the regression test coverage failed. (Sorry to be such a noob... :)

**Comment by mcking65** [comment]
Thank you @carmacleod!

**Comment by nschonni** [comment]
> forgive my inexperience with Travis here, but I'm not sure how to tell that the [overall build](https://travis-ci.com/github/carmacleod/aria-practices/jobs/361077898) was marked as passed?

@carmacleod if you see the green checkmark next to the commit, then the overall job is passing or from the first paragraph of the `checks` page on a PR.
I agree it can be kind of confusing. There docs talk a little bit about it https://docs.travis-ci.com/user/customizing-the-build/#jobs-that-are-allowed-to-fail, but I think they avoid the overall red X so people don't get used to ignoring those on the main build page.

I did find the fact that you can't currently do this with the GitHub Actions a little annoying when playing around with https://github.com/w3c/aria-practices/pull/1385

**Comment by carmacleod** [comment]
Aha! Thanks again @nschonni . I was looking at it from the build link that was sent to me in email (for some reason, build links started showing up in my email recently). I see that it's much clearer if you go to the PR and look at the build info from that angle. :)
I appreciate your patience!

**Pull request merged**
