### PR TITLE
Updated Treeview examples

### PR DESCRIPTION
**Pull request by jongund**
* Updated to latest example template
* Updated titles to be more consistent with other examples
* Fixed some bugs

### CODE REVIEW

**Comment by mcking65** [comment]
@jongund,

Thank you for these many improvements. Might you be able to add some commits to do the following?

-[ ] Fix misspellings in the intro paragraphs
- [ ] Use `<kbd>key name</kbd>` in the keyboard table without the word "key"
- [ ] Add row headers to the keyboard and states/props tables using `<th scope="row"</th>` as is done in the [example template](https://github.com/w3c/aria-practices/blob/master/examples/coding-template/Example-Template.html)

**Comment by jongund** [comment]
Matt,

I can do the fixes to kbd element.

Do we really need scope=row on these tables?

Jon

**Comment by mcking65** [comment]
scope=row is necessary in the states/prop table due to the empty cells. Otherwise screen readers will sometimes read a row header as a col header.

It is pretty confusing without the scope.

**Comment by jongund** [comment]
Matt,

I finished treeview and there is a pending pull request the changes should be included in.
Let me know if they don’t come through.

I will try to make these changes to the other examples by tomorrow morning (if they are missing).
Menu button
Menubar
Checkbox
Radiogroup


Jon

**Comment by mcking65** [comment]
@jongund,

John, there is one other issue to watch for. When linking back to the practices document, we omit the file name from the href.

This is because the file does not stay aria-practices.html when published to github.io or when it gets to the w3.org/tr site.
In both of those cases, the main document is the default file for the site.

So, if linking back to the treeview pattern, the link is:
`<a href="../../../#TreeView">tree view design pattern</a>`

Because of that, it may appear broken locally in your repo, but it is not broken after publication.

We considered renaming the aria-practices.html file to index.html, but decided not to do so ... at least not for now. In the main doc, such transforms are handled by respec. And, we do not want to add respec to the example pages.

**Comment by jongund** [comment]
Ok I will fix

**Comment by jongund** [comment]
I have fixed the links back to the aria practices document

**Comment by mcking65** [comment]
@jongund,

Thank you ... merging. 

You added scope="col" to column headers. But, the tables still do not have row headers. I can do it when I take care of final editorial cleanup.

**Comment by jongund** [comment]
I see I still need to add TH scope=row to the tables   I can do that tomorrow (Sunday)   I also need to add some sections on related examples at least for treeview.

Jon  Gunderson
Sent from my iPhone

On Dec 9, 2016, at 10:50 PM, Matt King <notifications@github.com<mailto:notifications@github.com>> wrote:


Merged #195<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_w3c_aria-2Dpractices_pull_195&d=DQMCaQ&c=8hUWFZcy2Z-Za5rBPlktOQ&r=REZD8fc2AwufInstfW3L5jSLVS8bjZtAodDOhat7yAI&m=rP7sB-LhJj67h_cjzZDyGh8oqwRVCOPJFSqZnB2wABE&s=E4HlSnNfAR9ixBs1vhCFjF2koS5Rhlblwr-dlECbZvU&e=>.

**Pull request merged**
