### PR TITLE
fix: Schonni -> Schonning

### PR DESCRIPTION
**Pull request by nschonni**
It's shortened in my GitHub username because of old university naming conventions and momentum.

***
<a href="https://pr-preview.s3.amazonaws.com/nschonni/aria-practices/pull/1022.html" title="Last updated on Jun 10, 2019, 5:47 AM UTC (cdcade7)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/aria-practices/1022/8bfd5bc...nschonni:cdcade7.html" title="Last updated on Jun 10, 2019, 5:47 AM UTC (cdcade7)">Diff</a>

### CODE REVIEW

**Comment by nschonni** [comment]
Repoening because "Travis CI - Branch" seems to be stuck

**Comment by mcking65** [comment]
I wonder if our travis and branch configurations have blocked our ability to merge anything from a fork or patch directly into master. I see the following on all such PRs:

>1 expected and 1 successful checks

Apparently, travis is attempting to test both the branch in the fork and the PR. I'm not clear on why it has to run the same tests two different ways. If testing the PR is essentially testing the result of the merge, why does it need to separately test the branch?

It would seem the only way we can merge from forks is if the submitter of a PR has travis set up on their fork so we can get the status back from it? That seems unreasonable. But, merging to a feature branch and then creating another PR to merge to master is unnecessary overhead, and would wipe out the attribution to the contributor unless the contributor can create the second PR as well.

@sh0ji, thoughts?

**Comment by nschonni** [comment]
I think it might be a GitHub policy that you've enabled. I think you made the "Travis CI -Branch" a required build in the repo setting. I actually do have Travis Setup in my repo (although on .org still rather than .com). I believe the "Branch" build only applies to branches of this repo, when you made it required

**Comment by sh0ji** [comment]
@nschonni is right. Since users need to submit PRs through a fork, it means their branch is owned by them and they have to set up Travis in it in order for the branch checks to run.

**Comment by mcking65** [comment]
OK, we have branch checks turned off now so now I can merge.

**Pull request merged**
