### PR TITLE
Button Examples (IDL Version): Clarify purpose and code for issue 727

### PR DESCRIPTION
**Pull request by carmacleod**
Closes issue #727 
- clarify purpose of example
- remove "similar examples" list
- set reflected attributes in init()
- add "equivalent to" comments

### CODE REVIEW

**Comment by carmacleod** [comment]
NOTE 1: This looks like a lot of changes, but it's not really. The easiest way to see these code changes is to compare `button.html` with `button_idl.html`, and `button.js` with `button_idl.js`. (Not sure how to do that in github... I was using my IDE to compare).

**Comment by carmacleod** [comment]
NOTE 2: To test, need to do the following:

Chrome: Enable chrome://flags/#enable-experimental-web-platform-features
(note: don't need to use Chrome Canary - just need to enable flag)

Edge: Use [Edge Beta, Dev or Canary](https://www.microsoftedgeinsider.com/en-us/download) and enable edge://flags/#enable-experimental-web-platform-features

Firefox: not supported yet, not even in beta with accessibility.AOM.enabled=true on the about:config page

Safari: [stand by... will test tomorrow]

Preview link for testing: https://raw.githack.com/w3c/aria-practices/car/issue727/examples/button/button_idl.html

**Comment by JAWS-test** [comment]
Problem in IE 11:
* SVG graphic is not displayed
* SVG graphic gets focus (focusable=false missing)

**Comment by carmacleod** [comment]
`[role="button"]`

**Comment by carmacleod** [comment]
Thanks for the review, @JAWS-test !

> Problem in IE 11:
> SVG graphic is not displayed
- All of the CSS in `button.css` keys off of `[role="button"]`, and so if that is not being set properly, then the example looks very strange. I suspect that is what is happening in IE11.

> SVG graphic gets focus (focusable=false missing)
- Thank-you! Added.

> Link "IDL Interface defined in ARIA 1.2" refers to the same page, but should probably refer to ARIA 1.2
- I think (??) that the link will be corrected by respec after the `apg-1.2` branch is merged into `master`. @jnurthen Can you verify that this link is correctly specified? The code is `<a class="specref" href="#idl-interface">`.

**Comment by carmacleod** [comment]
Additional notes:
- @jongund I decided to continue to use `getElementById()` instead of switching to `createElement()`, but I did move the setting of `.role` and `.ariaPressed` into javascript instead of keeping it in the html. I think it's best if the code changes between the button and button IDL versions of the code are minimal so that the IDL changes very easy to see. Hope that's ok. Please compare the `init ()` function in `button.js` and `button_idl.js` to see what I mean.
- @mcking65 I deleted the "Similar examples" list from `button_idl.html` because those examples aren't similar (i.e. they do not use reflection).

**Comment by carmacleod** [comment]
@mcking65, I like all of your updates - thank-you! Feel free to merge. :)

**Pull request merged**
