### PR TITLE
Fixup ReSpec usage issues

### PR DESCRIPTION
**Pull request by marcoscaceres**
***

### :boom: Error: 504 Gateway Time-out :boom: ###

[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on Apr 15, 2020, 5:55 AM UTC)_.

<details>
<summary>More</summary>

PR Preview relies on a number of web services to run. There seems to be an issue with the following one:

:rotating_light: [Spec Generator](https://www.w3.org/2015/labs/) - Spec Generator is the web service used to build specs that rely on ReSpec.

:link: [Related URL](https://labs.w3.org/spec-generator/?type=respec&url=https%3A%2F%2Frawcdn.githack.com%2Fw3c%2Faria-practices%2Fc74e8e46b38c7df5f4c1079f8d3dedf5373af1ab%2Faria-practices.html%3FisPreview%3Dtrue)

```
<html><body><h1>504 Gateway Time-out</h1>
The server didn't respond in time.
</body></html>

```

_If you don't have enough information above to solve the error by yourself (or to understand to which web service the error is related to, if any), please [file an issue](https://github.com/tobie/pr-preview/issues/new?title=Error%20not%20surfaced%20properly&body=See%20w3c/aria-practices%231376.)._
</details>

### CODE REVIEW

**Comment by jnurthen** [comment]
Thanks - had #1374 open for most of those. I'll close that in favour of this one

**Comment by marcoscaceres** [comment]
ah, woopsy, thanks.

**Comment by marcoscaceres** [comment]
It might be good to add support for "respec validator": 
https://github.com/marcoscaceres/respec-validator

It would catch errors like this before they get merged.

Alternatively, if you are auto-publishing this spec to /TR/ on merge, you can use:
https://github.com/w3c/respec-w3c-auto-publish

Which will also run the validator for you before publishing automatically to TR.

**Comment by jnurthen** [comment]
@marcoscaceres absolutely.
I'll raise this at the editors meeting.

pr-preview still appears borked but it seems to be picking up an old build. I have no idea where those scripts live in this repository but thanks so much for your help. I'm going to merge this despite the broken pr-preview as the changes seem pretty safe - and it is running without errors locally.

**Pull request merged**
