### PR TITLE
Toolbar - Set focus to first button with tabindex="0" when the container is clicked

### LINKED ISSUE #987: Toolbar Example: Make clicking padding move focus into toolbar
Per [comment in issue 539](https://github.com/w3c/aria-practices/issues/539#issuecomment-454870090)
by @sh0ji about the [toolbar example](http://w3c.github.io/aria-practices/examples/toolbar/toolbar.html),
make clicking the padding of the toolbar (the gray #ECECEA part) move focus into the toolbar.
This enables people to use their mouse to orient their focus and then use their keyboard to navigate inside the toolbar.

### PR DESCRIPTION
**Pull request by maschad96**
Resolves #987

[Preview Link](https://raw.githack.com/maschad96/aria-practices/maschad96/toolbar/set-focus-on-container-click/examples/toolbar/toolbar.html)

The issue mentions that:
- When focus is on a button, a focus ring is shown around the toolbar container.
- As a result, it conveys visually that focus is managed within that larger container

This approach basically adds another prototype method for `handleContainerClick`, comparing `this.domNode` to `event.target` to determine if it should set focus.

Open to feedback and other approaches. Thanks!

### Review checklist

* [ ] [Functional review](https://github.com/w3c/aria-practices/wiki/Pull-Request-Review-Process#functional_review) by @jongund
* [ ] [Code review](https://github.com/w3c/aria-practices/wiki/Pull-Request-Review-Process#code_review) by @smhigley

***
<a href="https://pr-preview.s3.amazonaws.com/maschad96/aria-practices/pull/1384.html" title="Last updated on Jul 21, 2020, 6:27 AM UTC (c848350)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/aria-practices/1384/2ddb55d...maschad96:c848350.html" title="Last updated on Jul 21, 2020, 6:27 AM UTC (c848350)">Diff</a>

### CODE REVIEW

**Comment by jongund** [comment]
@marcoscaceres 
@mcking65 
Thank you for the pull request, this is a good addition.
But instead of putting focus on the first item, I think it should put focus on the item with `tabindex=0`.   

So need to create method called 'setFocusCurrentItem` that can be called by the toolbar `onclick` event.  The method would go through the `toolbarItems` array looking for the one with `tabindex=0` and then use that to set focus.

**Comment by maschad96** [comment]
Thanks for the idea, @jongund. I've pushed up a new commit adding `FormatToolbar.prototype.setFocusCurrentItem` and now am calling that instead.

**Comment by mcking65** [comment]
@maschad96, thank you very much for this fix!

@jongund, can you take one last look and submit a review of the functionality, e.g., does it functionally resolve the issue in the desired way?

@smhigley, could you please submit a review of the code?

**Comment by maschad96** [comment]
@jongund I would agree that a new test should be added. I'll update later today.

**Comment by spectranaut** [comment]
hi @maschad96 ! Thanks for contributing this fix. It would be great if you could still write a test, and I thought I'd give you some pointers in case you haven't written test before.

[The documentation for our regression tests are in the wiki](https://github.com/w3c/aria-practices/wiki/Regression-Tests-for-APG-Example-Pages). The tests for this example are in [this file](https://github.com/w3c/aria-practices/blob/master/test/tests/toolbar_toolbar.js), unfortunately, you have contributed to the one example with pretty incomplete tests, so you might want to look at a different test file to get a picture of how the tests are written.

Additionally, most tests are of the accessibility features listed in the example. Each row in the "Keyboard Support" and "Role, Property, State, and Tabindex Attributes" have tests. But we have been wanted to write more regression tests for other behaviors not covered there, like this one. To do this, you just write a normal test, but you "tests-additional-behavior" for the "data-test-id" attribute. See the example in [the documentation](https://github.com/w3c/aria-practices/wiki/Regression-Tests-for-APG-Example-Pages#writing-additional-tests-tests-for-behavior-not-covered-in-the-keyboard-or-attributes-tables).

Feel free to ping me here or in the #aria-at irc channel on w3.org if you have questions :)

**Comment by maschad96** [comment]
Hi @spectranaut , thanks for the guidance! The links were very helpful for me, good to have. I've added some tests for keyboard and focus assertions. I'll send up some tests for tabindex and other attributes today or early this week. 😁

**Comment by spectranaut** [comment]
Closing this PR -- I adopted the code to get these long overdue changes in :) #1700

**Pull request closed without merging**
