### PR TITLE
chore: Use Travis Build stages

### PR DESCRIPTION
**Pull request by nschonni**
Related to #848
This will add 2 separate builds to separate out the linting and HTML validation so there are separate results reported

### CODE REVIEW

**Comment by mcking65** [comment]
@Nschonni, thank you for working on this!

To take it for a test spin, I installed travis in my personal account and ran this new setup with a PR in a fork of the repo. I used your cSpell as the test PR in the fork. [This is the checks page](https://github.com/mcking65/aria-practices/pull/2/checks) for that PR.

It's interesting that the badge on the checks tab in the navigation says there is one check but the summary in the conversation tab says 2 of 2 checks passed. The summary seems to be talking about the stages.

At any rate, here is what I see for the test stage on the checks page:

>Stage 1: Test
>
>This stage passed.
>
>Job
>Node.js
>State
>1.1
>node
>passed
>1.2
>node
>passed

Do you know if there is a way to get some more descriptive info there so it is easy to see what type of test is being done by each job?

I'd like to run one with some failures. This PR was failing in the w3c repo, but didn't fail in my fork. So, my next step is to create a few different kinds of errors and see how that looks; just didn't get that far this morning.

**Comment by mcking65** [comment]
Hmm ... wonder what is wrong.

In test PR 1 in my personal fork of aria-practices, I created a validation error (missing closing `li`) on [line 800 of aria-practices.html](https://github.com/mcking65/aria-practices/pull/1/files), but all [checks passed](https://github.com/mcking65/aria-practices/pull/1/checks).

**Comment by nschonni** [comment]
They could be more descriptive if we name the stages i think. That means they won't run in parallel though.
An alternate might be to add an environment variable with the job/npm task since I think the environment variables may show up in the jobs matrix

**Comment by nschonni** [comment]
Aside: I wonder if we could get the undocumented log fold regions to be created as landmarks https://github.com/travis-ci/docs-travis-ci-com/issues/949

**Comment by nschonni** [comment]
@mcking65 figured out how to name the jobs https://docs.travis-ci.com/user/customizing-the-build/#naming-jobs-within-matrices
Not sure why the "Deploy" stage is running even though it's filtered. I'll look at that and the missing validation separately

**Comment by nschonni** [comment]
> In test PR 1 in my personal fork of aria-practices, I created a validation error (missing closing li) on line 800 of aria-practices.html, but all checks passed.

Had to look it up, but it looks like tag ommision is OK for `<li>` if the next tag is an `<li>` https://developer.mozilla.org/en-US/docs/Web/HTML/Element/li

**Comment by nschonni** [comment]
OK, think I've got it sorted now.
1. The 2 linting jobs run separately in parallel with titles (and @spectranaut regression stuff can get added as another)
2. The deploy stage only runs when a commit is made to master and not on PRs to master

@mcking65 do you want to try this in your fork since my Travis setup was old and I don't have the checks API for this repo

**Comment by mcking65** [comment]
@nschonni, I wonder if I'm not doing some part of the testing correctly or if I have the mcking65/aria-practices repo properly configured.

1. I merged this latest version of .travis.yml into master in the mcking65 fork and pushed it.
2. I introduced some more errors into the jongund-combobox1.0 branch in the mcking65 fork and pushed those so they would show up in pull request 1.
3. The build re-ran, I assume using the new travis.yml in master. I'm assuming that the travis.yml in the jongund-combobox1.0 branch is irrelevant.

I expected the job names to show on the [checks page of pr 1](https://github.com/mcking65/aria-practices/pull/1/checks). I don't see them there.

Aside, the checks API description also led me to think that we could see the errors on the checks page and inline on the files page. Do you know if github and travis have done something to make that magically simple? Or, would we have to write a bunch of code to run our tests in a different way that feeds the API instead of just dumping to a log?

**Comment by nschonni** [comment]
ah, it's not showing up on yours because I rebased this down to a new commit when I figure out the job names. If you look at https://travis-ci.org/w3c/aria-practices/builds/422376484?utm_source=github_status&utm_medium=notification it's add the job names like:
```html
<div class="job-name">
    <span class="label-align" aria-label="Title">JS Linting</span>
  </div>
```
If you copy the current travis.yml into your branch it may show something different for the checks. I agree this is probably OK to merge now though

**Pull request merged**
