### PR TITLE
Fix color contrast of code comments in examples

### PR DESCRIPTION
**Pull request by carmacleod**
Noted during accessibility review of PR https://github.com/w3c/aria-practices/pull/1120.
Code comments on the example page fail the WCAG 4.5:1 contrast check.
The tabbed carousel example is apparently the first example to have comments in its HTML Source Code (which is shown with syntax highlighting on the example page).

Note 1: The fix in this PR is very simple, and takes advantage of the fact that at some point in the past, the APG examples overrode ReSpec's syntax highlighting by forking a local copy of github.css and making a color contrast fix. With this PR, there will be 2 contrast fixes in the APG copy of github.css.

Note 2: There have been [changes in ReSpec's syntax highlighting](https://github.com/w3c/respec/pull/2683) since the APG copy of github.css was forked. Notably:
- github.css was renamed highlight.css
- the content of the new file highlight.css was replaced with the [Atom One Light theme from highlight.js](https://github.com/highlightjs/highlight.js/blob/b7337391a18276c52b3d55b14117d3b3d6632f77/src/styles/atom-one-light.css)
- this means that ReSpec has a bunch of new syntax highlighting colors

Not sure if anyone wants to revisit possibly using the new ReSpec colors directly. @ZoeBijl ?
(If so, please note that [their comment color still doesn't pass](https://github.com/w3c/respec/issues/2737)!)

### Review checklist

* [x] [Visual design review](https://github.com/w3c/aria-practices/wiki/Pull-Request-Review-Process#design_review) by Evan (@sh0ji) and Sarah (@smhigley)
* [x] [Accessibility review](https://github.com/w3c/aria-practices/wiki/Pull-Request-Review-Process#accessibility_review) by Evan (@sh0ji) and Sarah (@smhigley)
* [x] [Code review](https://github.com/w3c/aria-practices/wiki/Pull-Request-Review-Process#code_review) by Evan (@sh0ji) and Sarah (@smhigley)

### CODE REVIEW

**Comment by ZoeBijl** [comment]
This looks good to me—I took the liberty of doing all the reviews.

**Comment by mcking65** [comment]
@ZoeBijl, please be careful to follow the [Protected Branch Pull Request Management and Merge Process](https://github.com/w3c/aria-practices/wiki/Protected-Branch-Pull-Request-Management-and-Merge-Process). In particular, using the squash merge method and titling commits for the change log.

**Comment by ZoeBijl** [comment]
@mcking65 which part did I miss? I updated the branch, renamed the commit, and did a squash merge.

**Comment by mcking65** [comment]
@ZoeBijl, very sorry, my bad ... i totally misread the history ... maybe I should have actually been all the way asleep at that time :( Looking now, and it looks great.

**Comment by ZoeBijl** [comment]
@mcking65 no worries! And please don't hesitate to mention it if I do mess up in the future :)

**Pull request merged**
