### PR TITLE
chore: Stylelint no-descending-specificity

### LINKED ISSUE #1522: Stylelint issues for no-descending-specificity
Stylelint hasn't been running because of a config file issue, and these rules are introduced over a few PRs.
I've cleaned up a bunch in #1518, there there are some remaining issues for these rules that will be suppressed temporarily and tracked here

```
2020-09-07T19:12:20.2013871Z examples/carousel/css/carousel-prev-next.css
2020-09-07T19:12:20.2024859Z ##[error] 211:1  ✖  Expected selector ".carousel-moreaccessible .carousel-items .carousel-image a" to come before selector ".carousel .carousel-item .carousel-caption a:hover"                            no-descending-specificity
2020-09-07T19:12:20.2030693Z ##[error] 211:1  ✖  Expected selector ".carousel-moreaccessible .carousel-items .carousel-image a" to come before selector ".carousel .carousel-item .carousel-caption a:focus"                            no-descending-specificity
2020-09-07T19:12:20.2032118Z ##[error] 240:1  ✖  Expected selector ".carousel-moreaccessible .carousel-item .carousel-caption a" to come before selector ".carousel .carousel-item .carousel-caption a:hover"                           no-descending-specificity
2020-09-07T19:12:20.2033339Z ##[error] 240:1  ✖  Expected selector ".carousel-moreaccessible .carousel-item .carousel-caption a" to come before selector ".carousel .carousel-item .carousel-caption a:focus"                           no-descending-specificity
2020-09-07T19:12:20.2034550Z ##[error] 240:1  ✖  Expected selector ".carousel-moreaccessible .carousel-item .carousel-caption a" to come before selector ".carousel-moreaccessible .carousel-items.focus .carousel-image a"             no-descending-specificity
2020-09-07T19:12:20.2035775Z ##[error] 250:1  ✖  Expected selector ".carousel-moreaccessible .carousel-item .carousel-caption span.contrast" to come before selector ".carousel .carousel-item .carousel-caption span.contrast:hover"   no-descending-specificity
2020-09-07T19:12:20.2037039Z ##[error] 280:1  ✖  Expected selector ".carousel-moreaccessible .controls" to come before selector ".carousel.carousel-moreaccessible .controls"                                                           no-descending-specificity
2020-09-07T19:12:20.2039008Z 
2020-09-07T19:12:20.2039505Z examples/carousel/css/carousel-tablist.css
2020-09-07T19:12:20.2040262Z ##[error] 272:1  ✖  Expected selector ".carousel-tablist-moreaccessible .carousel-items .carousel-image a" to come before selector ".carousel-tablist .carousel-item .carousel-caption a:hover"                            no-descending-specificity
2020-09-07T19:12:20.2041442Z ##[error] 272:1  ✖  Expected selector ".carousel-tablist-moreaccessible .carousel-items .carousel-image a" to come before selector ".carousel-tablist .carousel-item .carousel-caption a:focus"                            no-descending-specificity
2020-09-07T19:12:20.2042872Z ##[error] 301:1  ✖  Expected selector ".carousel-tablist-moreaccessible .carousel-item .carousel-caption a" to come before selector ".carousel-tablist .carousel-item .carousel-caption a:hover"                           no-descending-specificity
2020-09-07T19:12:20.2044074Z ##[error] 301:1  ✖  Expected selector ".carousel-tablist-moreaccessible .carousel-item .carousel-caption a" to come before selector ".carousel-tablist .carousel-item .carousel-caption a:focus"                           no-descending-specificity
2020-09-07T19:12:20.2045028Z ##[error] 301:1  ✖  Expected selector ".carousel-tablist-moreaccessible .carousel-item .carousel-caption a" to come before selector ".carousel-tablist-moreaccessible .carousel-items.focus .carousel-image a"             no-descending-specificity
2020-09-07T19:12:20.2045960Z ##[error] 311:1  ✖  Expected selector ".carousel-tablist-moreaccessible .carousel-item .carousel-caption span.contrast" to come before selector ".carousel-tablist .carousel-item .carousel-caption span.contrast:hover"   no-descending-specificity
2020-09-07T19:12:20.2047096Z ##[error] 354:1  ✖  Expected selector ".carousel-tablist-moreaccessible [role="tab"] circle.border" to come before selector ".carousel-tablist [role="tab"]:focus circle.border"                                           no-descending-specificity
2020-09-07T19:12:20.2048104Z ##[error] 354:1  ✖  Expected selector ".carousel-tablist-moreaccessible [role="tab"] circle.border" to come before selector ".carousel-tablist [role="tab"]:hover circle.border"                                           no-descending-specificity
2020-09-07T19:12:20.2049065Z ##[error] 358:1  ✖  Expected selector ".carousel-tablist-moreaccessible [role="tab"] circle.tab" to come before selector ".carousel-tablist [role="tab"][aria-selected="true"] circle.tab"                                 no-descending-specificity
2020-09-07T19:12:20.2050683Z ##[error] 358:1  ✖  Expected selector ".carousel-tablist-moreaccessible [role="tab"] circle.tab" to come before selector ".carousel-tablist [role="tab"]:hover circle.tab"                                                 no-descending-specificity
2020-09-07T19:12:20.2052148Z ##[error] 358:1  ✖  Expected selector ".carousel-tablist-moreaccessible [role="tab"] circle.tab" to come before selector ".carousel-tablist [role="tab"][aria-selected="true"]:hover circle.tab"                           no-descending-specificity
2020-09-07T19:12:20.2053212Z ##[error] 362:1  ✖  Expected selector ".carousel-tablist-moreaccessible [role="tab"] circle.tab-background" to come before selector ".carousel-tablist [role="tablist"].focus circle.tab-background"                       no-descending-specificity
2020-09-07T19:12:20.2054412Z ##[error] 362:1  ✖  Expected selector ".carousel-tablist-moreaccessible [role="tab"] circle.tab-background" to come before selector ".carousel-tablist [role="tab"]:hover circle.tab-background"                           no-descending-specificity
2020-09-07T19:12:20.2054768Z 
2020-09-07T19:12:20.2055368Z examples/combobox/css/combobox-datepicker.css
2020-09-07T19:12:20.2056293Z ##[error]  71:1  ✖  Expected selector ".combobox-datepicker .group.focus polygon" to come before selector ".combobox-datepicker .group button[aria-expanded="true"] polygon"   no-descending-specificity
2020-09-07T19:12:20.2057461Z ##[error] 112:1  ✖  Expected selector ".combobox-datepicker .dialog button" to come before selector ".combobox-datepicker .group.focus button"                                 no-descending-specificity
2020-09-07T19:12:20.2059349Z ##[error] 117:1  ✖  Expected selector ".combobox-datepicker .dialog button::-moz-focus-inner" to come before selector ".combobox-datepicker .group.focus button"               no-descending-specificity
2020-09-07T19:12:20.2060341Z ##[error] 165:1  ✖  Expected selector ".combobox-datepicker .dialog-ok-cancel-group button" to come before selector ".combobox-datepicker .group.focus button"                 no-descending-specificity
2020-09-07T19:12:20.2061811Z ##[error] 165:1  ✖  Expected selector ".combobox-datepicker .dialog-ok-cancel-group button" to come before selector ".combobox-datepicker .dialog button::-moz-focus-inner"    no-descending-specificity
2020-09-07T19:12:20.2062953Z ##[error] 237:1  ✖  Expected selector ".combobox-datepicker .dates td:focus" to come before selector ".combobox-datepicker .dates td:not(.disabled):hover"                     no-descending-specificity
2020-09-07T19:12:20.2063291Z 
2020-09-07T19:12:20.2063695Z examples/menubar/css/menubar-editor.css
2020-09-07T19:12:20.2064564Z ##[error] 104:1  ✖  Expected selector ".menubar-editor [role="menubar"] [role="separator"]" to come before selector ".menubar-editor [role="menubar"] [role="menu"] [role="separator"]"   no-descending-specificity
2020-09-07T19:12:20.2065520Z ##[error] 127:1  ✖  Expected no more than 1 empty line                                                                                                                                    max-empty-lines          
2020-09-07T19:12:20.2065878Z 
2020-09-07T19:12:20.2066291Z examples/menubar/css/menubar-navigation.css
2020-09-07T19:12:20.2067113Z ##[error] 36:1  ✖  Expected selector ".menubar-navigation [role="menuitem"]" to come before selector ".menubar-navigation [role="menu"] [role="menuitem"]"          no-descending-specificity
2020-09-07T19:12:20.2068120Z ##[error] 37:1  ✖  Expected selector ".menubar-navigation [role="separator"]" to come before selector ".menubar-navigation [role="menu"] [role="separator"]"        no-descending-specificity
2020-09-07T19:12:20.2069055Z ##[error] 68:1  ✖  Expected selector ".menubar-navigation > li > [role="menuitem"]" to come before selector ".menubar-navigation [role="menu"] [role="menuitem"]"   no-descending-specificity
2020-09-07T19:12:20.2069978Z ##[error] 88:1  ✖  Expected selector ".menubar-navigation [role="separator"]" to come before selector ".menubar-navigation [role="menu"] [role="separator"]"        no-descending-specificity
```

### PR DESCRIPTION
**Pull request by nschonni**
https://stylelint.io/user-guide/rules/no-descending-specificity

Fixes #1522

### CODE REVIEW

**Review by spectranaut — APPROVED** [review]
This looks good! but the changes for the navigational menubar CSS file will conflict with this PR: https://github.com/w3c/aria-practices/pull/1612

Not sure which one we should land first.

**Comment by nschonni** [comment]
I'm happy the let the functional stuff land first and rebase afterwards to make it easier

**Comment by mcking65** [comment]
@nschonni, 2 questions:

1. Does this resolve all the errors listed in #1522?
2. Will this create conflicts with #1612 that @jongund will need to resolve? It's OK if it does; I just want Jon to be aware. Alternatively, we could wait till after #1612 is merged and then do this.

**Comment by nschonni** [comment]
@mcking65 Yes, I've marked this so it will automatically close #1522 when it lands.
I think it might conflict with #1612, and I'm ok waiting till that lands to make it easier for @jongund

**Review by mcking65 — APPROVED** [review]
Thank you @nschonni!

**Pull request merged**
