### PR TITLE
Guidelines for aria-level attribute

### PR DESCRIPTION
**Pull request by spectranaut**
[Rendered](https://github.com/bocoup/aria-practices/blob/aria-level/describing-hierachical-structure-with-aria-level.md)

Including this open issue on ARIA: https://github.com/w3c/aria/issues/915

@zcorpan

***
<a href="https://pr-preview.s3.amazonaws.com/bocoup/aria-practices/pull/1003.html" title="Last updated on Jul 19, 2019, 9:16 PM UTC (a039365)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/aria-practices/1003/eab169c...bocoup:a039365.html" title="Last updated on Jul 19, 2019, 9:16 PM UTC (a039365)">Diff</a>

### CODE REVIEW

**Comment by mcking65** [comment]
@spectranaut, should we close this PR and replace it with one from the aria-level branch? I didn't compare this bocoup:aria-level branch to the w3c:aria-level branch, but I do see you committed to w3c:aria-level on June 26. So, I am guessing the one in the w3c repo is actually the latest work?

**Comment by spectranaut** [comment]
I just compared and actually bocoup:aria-level has two more commits than w3c:aria-level (they are otherwise identical) -- I might have accidentally pushed to w3c:aria-level instead of bocoup:aria-level once. I'm going to delete the branch on w3c to avoid confusion in the future!

**Comment by mcking65** [comment]
I prefer to work on a branch in the w3c repo. I will make a new one and land this work there.

**Comment by mcking65** [comment]
@spectranaut, could you please create a new PR with a compare branch of issue259-aria-level-guidance and base branch of master?

**Comment by spectranaut** [comment]
sure thing :)

**Pull request merged**
