### PR TITLE
Infrastructure: update skipto.js to version 5.2.1

### PR DESCRIPTION
**Pull request by jongund**
Updated skip.js to use public distribution.
This requires scripts referencing `skipto.js` to include the following data attribute:
```
  <script data-skipto="colortheme: aria; displayoption: popup" src="../../shared/js/skipto.js"></script>
```
 
This is related to [issue 259](https://github.com/w3c/wai-aria-practices/issues/259) in wai-aria-practices repository.
___
[WAI Preview Link](https://deploy-preview-260--aria-practices.netlify.app/ARIA/apg) _(Last built on Tue, 06 Feb 2024 22:25:28 GMT)._

### CODE REVIEW

**Review by mcking65 — CHANGES_REQUESTED** [review]
@jongund rather than add colortheme and displayoption to cspell, I think we should change the syntax to use either color-theme and display-option or colorTheme and displayOption. I am pretty sure either would get past cspell. What is your preference?

Also, a navigation region is getting wrapped around the skipto button. We don't want that. We need an option to suppress. Or, better yet, the default should be to not add it. Skipto is the first thing on the page. The nav region is not useful in practice, and it adds extra verbosity that is distracting when tabbing.

**Comment by jongund** [comment]
The keywords are case insenstative, so the following updated configuration should fix the cspell issue and the navigation landmark problem is fixed by adding the `containerElement` option.

```
  <script data-skipto="colorTheme:aria; displayOption:popup; containerElement:div" src="../../shared/js/skipto.js"></script>
```

**Review by mcking65 — APPROVED** [review]

**Comment by mcking65** [comment]
Thanks @jongund. That solved the problems.

This PR now provides the updated skipto with appropriate behaviors on all pages except for three:
1. [APG Home](https://deploy-preview-260--aria-practices.netlify.app/aria/apg/)
2. [Patterns | APG | WAI | W3C](https://deploy-preview-260--aria-practices.netlify.app/aria/apg/patterns/)
3. [Practices | APG | WAI | W3C](https://deploy-preview-260--aria-practices.netlify.app/aria/apg/practices/)

Since #2702, is not yet done, we will need to address the update of skipto for these three pages in wai-aria-practices via w3c/wai-aria-practices#259. We need to determine how that will be resolved before we merge this.

@a11ydoer, I'm assigning you as a reviewer to look at the visual presentation and mouse behavior of this version to make sure there are no regressions or unexpected changes.

**Review by a11ydoer — APPROVED** [review]
Navigation with keyboard only or mouse works.

**Comment by howard-e** [comment]
@mcking65 @a11ydoer @jongund this PR has been updated with the suggested change to `patterns.html` and `practices.html` to include the `data-skipto` attributes in the `skipto` script import for those pages.

The [preview link](https://deploy-preview-260--aria-practices.netlify.app/aria/apg/) has also been rebuilt.

**Pull request merged**
