### PR TITLE
Landmark examples: Update links to related documents and SkipTo script 

### PR DESCRIPTION
**Pull request by jongund**
Also made some minor edits to the resources page 
___
[WAI Preview Link](https://deploy-preview-198--aria-practices.netlify.app/ARIA/apg) _(Last built on Sun, 11 Jun 2023 00:58:36 GMT)._

### CODE REVIEW

**Comment by jongund** [comment]
@mcking65 
Not sure why one of the regression tests is failing for toolbar, none of the toolbar files were changed in this pull request.

**Comment by howard-e** [comment]
@jongund I I'm assuming it's a flaky test because the related `pull_request` action ran successfully, but the `push` action did not. So I went ahead and re-ran the action (and it now passes).

For context, the error was reported as a timeout by the test runner.

<details>
<summary>Error:</summary>

```
not ok 92 - toolbar_toolbar › content/patterns/toolbar/examples/toolbar.html [data-test-id="toolbar-menuitemradio-aria-checked"]: menuitemradio elements have aria-checked set
  ---
    name: AssertionError
    message: Rejected promise returned by test
    values:
      'Rejected promise returned by test. Reason:': |-
        TimeoutError {
          remoteStacktrace: '',
          message: `Waiting for menu to open␊
          Wait timed out after 10141ms`,
        }
    at: |-
      Wait timed out after 10141ms
      node_modules/selenium-webdriver/lib/webdriver.js:929:17
      runMicrotasks (<anonymous>)
  ...
```
</details>

**Comment by jongund** [comment]
@howard-e 
Thank you for fixing the problem.  I tired rerunning the tests, but it still reported the problem.

**Comment by jongund** [comment]
@howard-e 
I made an update on this pull request, but the preview links failed to be created.
Who can look into this?

**Comment by howard-e** [comment]
@jongund the error described in [the failed build, under the 'Update site files' step](https://github.com/w3c/wai-aria-practices/actions/runs/5192225933/jobs/9361097955) is:

<details>
<summary>Error:</summary>

> /home/runner/work/wai-aria-practices/wai-aria-practices/scripts/pre-build/library/determineContentType.js:48
  throw new Error(
        ^
>
> Error: Could not determine content type for file at /home/runner/work/wai-aria-practices/wai-aria-practices/_external/aria-practices/content/about/introduction/introduction.html
This file may not follow established conventions.
    at determineContentType (/home/runner/work/wai-aria-practices/wai-aria-practices/scripts/pre-build/library/determineContentType.js:48:9)

</details>

The condition for this happening seems related to https://github.com/w3c/wai-aria-practices/issues/219 since that `w3c/wai-aria-practices` has been updated recently. I've manually updated the generated PR, https://github.com/w3c/wai-aria-practices/pull/198 and re-ran the action, so the link is now available.

**Review by mcking65 — APPROVED** [review]

**Pull request merged**
