### PR TITLE
Expand VNU validator file pattern

### PR DESCRIPTION
**Pull request by nschonni**
Realized that the original wasn't catching all subfolders. Fixed up the issues that I understood, but there are a few combobox examples using `rel` on `ul` and `li` elements that I don't understand enough to fix. EX: 
```
"file:/Users/nschonni/Documents/github/aria-practices/examples/menubar/menubar-2/menubar-2.html":57.11-57.63: error: Attribute “rel” not allowed on element “ul” at this point.
"file:/Users/nschonni/Documents/github/aria-practices/examples/menubar/menubar-2/menubar-2.html":67.13-67.77: error: Attribute “rel” not allowed on element “li” at this point.
"file:/Users/nschonni/Documents/github/aria-practices/examples/menubar/menubar-2/menubar-2.html":68.13-68.79: error: Attribute “rel” not allowed on element “li” at this point.
"file:/Users/nschonni/Documents/github/aria-practices/examples/menubar/menubar-2/menubar-2.html":71.15-71.72: error: Attribute “rel” not allowed on element “ul” at this point.
"file:/Users/nschonni/Documents/github/aria-practices/examples/menubar/menubar-2/menubar-2.html":79.15-79.82: error: Attribute “rel” not allowed on element “ul” at this point.
"file:/Users/nschonni/Documents/github/aria-practices/examples/menubar/menubar-2/menubar-2.html":90.11-90.67: error: Attribute “rel” not allowed on element “ul” at this point.
"file:/Users/nschonni/Documents/github/aria-practices/examples/menubar/menubar-2/menubar-2.html":101.13-101.73: error: Attribute “rel” not allowed on element “li” at this point.
"file:/Users/nschonni/Documents/github/aria-practices/examples/menubar/menubar-2/menubar-2.html":102.13-102.73: error: Attribute “rel” not allowed on element “li” at this point.
"file:/Users/nschonni/Documents/github/aria-practices/examples/menubar/menubar-2/menubar-2.html":105.15-105.71: error: Attribute “rel” not allowed on element “ul” at this point.
```
These can be ignored in the `.vnurc`, but I wanted to see if it was intentional first

### CODE REVIEW

**Comment by nschonni** [comment]
I rebased and there is another set of things being flagged for the accordion
```
"file:/Users/nschonni/Documents/github/aria-practices/examples/accordion/accordion.html":57.11-57.44: error: Bad value “heading” for attribute “role” on element “dt”.
"file:/Users/nschonni/Documents/github/aria-practices/examples/accordion/accordion.html":64.11-64.94: error: Bad value “region” for attribute “role” on element “dd”.
"file:/Users/nschonni/Documents/github/aria-practices/examples/accordion/accordion.html":99.11-99.44: error: Bad value “heading” for attribute “role” on element “dt”.
"file:/Users/nschonni/Documents/github/aria-practices/examples/accordion/accordion.html":106.11-106.101: error: Bad value “region” for attribute “role” on element “dd”.
"file:/Users/nschonni/Documents/github/aria-practices/examples/accordion/accordion.html":132.11-132.44: error: Bad value “heading” for attribute “role” on element “dt”.
"file:/Users/nschonni/Documents/github/aria-practices/examples/accordion/accordion.html":139.11-139.101: error: Bad value “region” for attribute “role” on element “dd”.
```

**Comment by Decrepidos** [comment]
Not sure if this is helpful but, I opened this as an issue previously. It was discussed and closed. https://github.com/w3c/html-aria/issues/110#issue The W3C Nu Html Checker flags role errors on the ARIA 1.1 Accordion design pattern. #110

**Comment by nschonni** [comment]
@Decrepidos thanks for pointing that one out! Seems like it's probably something to fix in the example rather than suppress in the linter then. I could suppress it for now, and keep an issue open to remove that later

**Comment by mcking65** [comment]
I've opened issue #815 to change accordion.

**Comment by mcking65** [comment]
@nschonni, this looks good. Unfortunately, I was out last week, and when I returned, I had to prioritize the changes needed for the regression test project. So, now some of the files you changed to fix validation errors conflict with changes we made for the regression test project.

I hope this isn't asking too much ... wondering if you would mind making a separate PR for fixing the validation errors and resolving the conflicts and a second one for the jar upgrade, expansion of coverage, and changes to .vnurc?

**Comment by nschonni** [comment]
@mcking65 I've split out the fixes. I'll rebase this branch once that lands

**Comment by nschonni** [comment]
@mcking65 I've rebased to remove the markup changes and created #822 for the validation errors for the menubar example.

**Comment by mcking65** [comment]
Thank you @nschonni! Extremely helpful!!

**Pull request merged**
