### PR TITLE
Infrastructure: Remove commenting from coverage-report.yml workflow

### PR DESCRIPTION
**Pull request by zcorpan**
Remove unsafe code, until we have a better solution. Myself or @jesdaigle will open a new issue with possible options for surfacing this information.

This workflow is currently manually disabled.

cc @nschonni @mcking65

### CODE REVIEW

**Comment by zcorpan** [comment]
The risk is mostly other people copying it, or someone enables the workflow not knowing about it being unsafe.

**Comment by nschonni** [comment]
The only one I believe that could re-enable the job is Michael. Forks need to turn on Actions manually

**Comment by mcking65** [comment]
Out of an abundance of caution, to satisfy the security team, I am OK with removing. However, I would like to see the issue with replacement options raised before we merge.

**Comment by zcorpan** [comment]
See #1811

**Comment by zcorpan** [comment]
@mcking65 the requested issue now exists; should we merge this now or wait for some discussion/progress in #1811?

**Review by jesdaigle — APPROVED** [review]

**Comment by nschonni** [comment]
Opened https://github.com/w3c/aria-practices/pull/1976 because the token can now be restricted to "issue writing" and nothing else

**Comment by nschonni** [comment]
@zcorpan think this one can be closed now with the other fix

**Pull request closed without merging**
