### PR TITLE
Change Michiel → Zoë

### PR DESCRIPTION
**Pull request by ZoeBijl**
Following my recent name change: change Michiel to Zoë in the editor section.

### CODE REVIEW

**Comment by jnurthen** [comment]
@ZoeBijl You probably also want to do a PR against aria-common in the file acknowledgements/aria-wg-active.html

**Comment by ZoeBijl** [comment]
> @ZoeBijl You probably also want to do a PR against aria-common in the file acknowledgements/aria-wg-active.html

Want me to add that to this PR? There are three other mentions, the acknowledgements and the DeletedSectionsArchive.

**Comment by jnurthen** [comment]
> > @ZoeBijl You probably also want to do a PR against aria-common in the file acknowledgements/aria-wg-active.html
> 
> Want me to add that to this PR? There are three other mentions, the acknowledgements and the DeletedSectionsArchive.

acknowledgements needs to be done in the aria-common repository - that section is maintained there and some @michael-n-cooper magic copies into each of the aria repositories so changing here would have no effect. 

For DeletedSectionsArchive that is up to you. I don't think there is any way to change already published material (like previous spec versions) and I see this as being a little like those but I certainly wouldn't object to any change if you want to make it.

**Comment by ZoeBijl** [comment]
@jnurthen can you merge this? I don’t have the rights.

**Comment by jnurthen** [comment]
Merged - @mcking65 I tried to cherry-pick this into apg-1.2 but it appears I don't have the rights to do that. Can you please ensure this gets merged into the 1.2 release too.

**Comment by michael-n-cooper** [comment]
I updated aria-common https://github.com/w3c/aria-common/commit/9651e17e27e6c9bbecb9d4bf74d7bec3033bb068

**Comment by ZoeBijl** [comment]
Thank you very much @jnurthen and @michael-n-cooper 💯

**Pull request merged**
