### PR TITLE
Abandened: Was merge from master into apg-1.1 but now into a temp throwaway branch

### PR DESCRIPTION
**Pull request by mcking65**
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/aria-practices/pull/1086.html" title="Last updated on Jul 14, 2019, 7:20 AM UTC (0d2eea6)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/aria-practices/1086/089049b...0d2eea6.html" title="Last updated on Jul 14, 2019, 7:20 AM UTC (0d2eea6)">Diff</a>

### CODE REVIEW

**Comment by mcking65** [comment]
Closing; trying another approach.

**Comment by mcking65** [comment]
Reopening because github won't let me delete this branch; will merge it into another throw away branch that is not protected.

**Comment by mcking65** [comment]
Damn, GitHub still will not let me delete the branch named apg-1.1-update, even after successfully merging it elsewhere. I don't understand. 

@michael-n-cooper 
Can you delete branch apg-1.1-update?

**Comment by michael-n-cooper** [comment]
The branch name was conflicting with wildcarding rules for protected branches. I adjusted the rule and was able to delete this branch.

**Pull request merged**
