### PR TITLE
Minor fixes to the bocoup branch

### PR DESCRIPTION
**Pull request by spectranaut**

### CODE REVIEW

**Comment by spectranaut** [comment]
@jessebeach maybe the last PR? :)

**Comment by mcking65** [comment]
@spectranaut, do you plan to add some more commits?

@jessebeach, @tatermelon, or @sh0ji, could you have a look at the feed, radio, and slider changes?

**Comment by spectranaut** [comment]
Nope, no more commits, @mcking65 !

**Comment by mcking65** [comment]
Hurray!!!!!!!!!!!!!! I'll do a merge to master after my next meeting!

**Pull request merged**
