### PR TITLE
fix: Add missing aria roles

### PR DESCRIPTION
**Pull request by nschonni**
Compared with MDN list

### CODE REVIEW

**Comment by jongund** [comment]
@nschonni 

Landmark roles are generated by a different method that the other aria roles, so we don't want them in the list.

**Comment by nschonni** [comment]
How does look with it commented out with a reason?

**Comment by mcking65** [comment]
Resolved by #1084.

**Comment by nschonni** [comment]
No problem, I'll do a PR for just the purposely skipped `region` value in the array

**Pull request closed without merging**
