### PR TITLE
Unnest treeview examples for consistency (issue 2418 task)

### PR DESCRIPTION
**Pull request by alflennik**
This PR makes the file structure of all examples consistent by fixing the inconsistently nested examples in the treeview pattern directory.

See a [comment in issue #2418](https://github.com/w3c/aria-practices/issues/2418#issuecomment-1237572551) for more information about this task.

This PR is dependent on other PRs. Once PRs #2499 and #2451 have been merged into #2417, the base of this PR can be changed from `move-examples-next` to `move-examples`. I created the `move-examples-next` branch to make writing and reviewing this PR easier.

### CODE REVIEW

**Review by mcking65 — CHANGES_REQUESTED** [review]
@alflennik, In treeview-1a.html and treeview-1b, the href of links to the design pattern and treeview-navigation.html need revision.

**Comment by alflennik** [comment]
Thank you @mcking65, it seems in my haste to scan for links to treeview-1a and treeview-1b I neglected to fix all the links going in the other direction. I fixed the broken links you referred to, and I went through all the links in the treeview directory to make sure there weren't any others.

**Review by mcking65 — APPROVED** [review]

**Comment by mcking65** [comment]
Thank you @alflennik! I changed base, fixed conflicts, and fixed one more href that was easy to miss. This is good to go now. I'll merge.

**Comment by alflennik** [comment]
Big thanks Matt for getting it over the finish line!

**Pull request merged**
