### PR TITLE
Landmark Example Pages: Restore list structure in page navigation region

### PR DESCRIPTION
**Pull request by WilcoFiers**
The bootstrap-accessibility.js file was putting role="presentation" on li element in the navigation for absolutely no reason. This causes the entire menu to end up as nav > ul > li[role=presentation]. This seemed unintentional. The fix is just to remove that .navpills class, which doesn't seem to be used in styles.

### CODE REVIEW

**Review by mcking65 — APPROVED** [review]
Thank you @WilcoFiers! LGTM, but since changes CSS, would like @jongund  to review to ensure there are no side effects I can't see.

**Review by jongund — CHANGES_REQUESTED** [review]
@WilcoFiers @mcking65 Thank you for your interest in the landmark example, it seems the change breaks the `aria-current="page"` visual styling for the example. 

[Preview Link I used](https://raw.githack.com/WilcoFiers/aria-practices/landmark-a11y-fixes/examples/landmarks/banner.html)

**Comment by ZoeBijl** [comment]
I’ve added a fix to @WilcoFiers’ branch.

**Comment by ZoeBijl** [comment]
@jongund I’m seeing the correct style on that link you used, maybe a cache issue?

the banner link highlighted in the menu

**Review by jongund — APPROVED** [review]

**Pull request merged**
