### PR TITLE
Moves feed delay menu to prior to feed.

### PR DESCRIPTION
**Pull request by aardrian**
Addresses #877.

### CODE REVIEW

**Comment by aardrian** [comment]
A client shared this example with me, without seeing the warnings and without this fix being in place (so I pointed them to this PR). Is there a reason not to merge this?

**Comment by mcking65** [comment]
Many apologies for being so tardy addressing this. I commented in #877 to explain why I think this may not be the change that would best serve the intent of the feed example. I think that is the better place to discuss this for now.

**Comment by ZoeBijl** [comment]
Todo:

- [ ] Add focusable after the feed
- [ ] Reference new focusable in [Feed invocation](https://github.com/w3c/aria-practices/blob/main/examples/feed/js/main.js#L19)

**Review by ZoeBijl — APPROVED** [review]

**Review by ZoeBijl — CHANGES_REQUESTED** [review]
Todo:

- [ ] Add focusable after the feed
- [ ] Reference new focusable in [Feed invocation](https://github.com/w3c/aria-practices/blob/main/examples/feed/js/main.js#L19)

**Comment by mcking65** [comment]
Addressed by #2775

**Pull request closed without merging**
