### PR TITLE
Infrastructure: update globs for file moves

### PR DESCRIPTION
**Pull request by nschonni**
Updates the globs for ESLint and cSpell so the CI goes green again after the moves

### CODE REVIEW

**Comment by nschonni** [comment]
@mcking65 this should make the other `move-examples` PRs easier to review, since the CI will flag new issues rather than ones that were previously ignored

**Comment by mcking65** [comment]
@nschonni 

wish I would have seen and merged this before I worked on the table pattern file. I just added the missing tag. So, it should be a snap to rebase this. Other changes look great, thank you!

**Comment by mcking65** [comment]
I just pushed commit to remove aria-practices-DeletedSectionsArchive.html from the move-examples branch.

It's is the time and place to make that change, finally!

**Comment by nschonni** [comment]
> wish I would have seen and merged this before I worked on the table pattern file. I just added the missing tag. So, it should be a snap to rebase this. Other changes look great, thank you!

@mcking65 I rebased out the tag change for this one



> I just pushed commit to remove aria-practices-DeletedSectionsArchive.html from the move-examples branch.

OK, I'll go update my review on that other PR then

**Review by mcking65 — APPROVED** [review]
Thank you @nschonni

**Pull request merged**
