### PR TITLE
Skipto menu on all pages: Update skipto.js script to version 5.1.6

### PR DESCRIPTION
**Pull request by jongund**
This update fixes the following issues:
1. Accessible name computation takes into account Firefox when there are img elements in a heading (H1-H6).
2. `skipto.js` will only load once, if the `skipto.js` is loaded more than once the successive loadings will be ignored and send a warning message to the console.
___
[WAI Preview Link](https://deploy-preview-215--aria-practices.netlify.app/ARIA/apg) _(Last built on Thu, 11 May 2023 14:18:55 GMT)._

### CODE REVIEW

**Comment by alflennik** [comment]
Thank you for opening this PR with the correct version of the library - since we decided to move this library to the wai-aria-practices repo I copied the new version over there and the PR is https://github.com/w3c/wai-aria-practices/pull/217. If that makes sense could you close this PR?

**Comment by jongund** [comment]
What ever works for the templates, but please use version 5.1.5 for all templates, since it will correctly identify if skipto.js is being loaded more than once.

**Comment by jongund** [comment]
@alflennik 
I updated SkipTo to version 5.1.6.
5.1.6 fixes a rare bug in computing landmarks when there are no headings in the main content.

**Comment by jongund** [comment]
@alflennik 
Could we add the following configuration script to the template?
The version I am butting in the pull request changes the default values of the following three options based on the preferences for the WAI/APG website.  
If we can add this configuration script to the template any updates to SkipTo can be more easily applied to the website, by a simple update of the unmodified script.

```
<script>
var SkipToConfig =  {
  displayOption: 'popup',
  containerElement: 'div',
  colorTheme: 'aria'
};
</script>
```

More information on configuration options:
[https://skipto-landmarks-headings.github.io/page-script-5/]

**Comment by jongund** [comment]
@alflennik @mcking65 
I have add a feature to `skipto.js` to configue it using the `data-skipto` attribute on the `script` tag.
So if you are interested you could download [version 5.2](https://skipto-landmarks-headings.github.io/page-script-5/dist/skipto.js) and use the following code to configure skipto for the APG website:

```
<script 
  data-skipto="displayOption: popup; containerElement: div; colorTheme: aria"
  src="WAI/content-assets/wai-aria-practices/shared/js/skipto.js">
</script>
```

**Comment by mcking65** [comment]
@charmarkk @ariellalgilmore @andreancardona @curtbellew @shirsha 

Are any of you available to do a quick review/test to ensure there are no regressions or new issues in this version of the skipto menu?

[This is the preview link to test.])https://deploy-preview-215--aria-practices.netlify.app/aria/apg/)

I am specifically looking for test of visual appearance, keyboard,  and mouse behavior in:
* Chrome, Edge,  and Firefox on Windows
* Chrome and Safari on macOS

I have tested with screen readers.

**Review by ariellalgilmore — APPROVED** [review]
LGTM visually on browsers!

**Comment by a11ydoer** [comment]
Overall it looks good to me. One thing I am curious about is that there is no focus indicator only for complementary landmark. @jongund, Is this perhaps the intended design?

**Comment by jongund** [comment]
@a11ydoer 
SkipTo looks for the first focusable element (e.g. link or form control) in the landmark and sets focus to the element.  If there is no link or form control, it will look to a header (h1-h6) and set focus to it.  It does this by temporally giving a tabindex=-1 and the using .focus method to set focus to the header. If no header is found it will just set focus to the container.

**Pull request merged**
