### PR TITLE
Landmark Example pages: Make HTML techniques tab active on page load

### PR DESCRIPTION
**Pull request by jongund**
Updated the landmark example to:
* Make the HTML technique the default rendering
* Removed Window Eyes from list of AT Supporting Landmarks
* Updated copyright 2020

### CODE REVIEW

**Comment by jongund** [comment]
@carmacleod 
I can fix VoiceOver, thanks for the quick review and the feedback.

**Comment by carmacleod** [comment]
Thanks @jongund  !
Verified again, and still +1  :)

**Comment by jongund** [comment]
@mcking65 
@spectranaut 
Travis CI is giving failing tests for examples unrelated to the landmark example pages.  
The only changes in the PR are in the landmarks example, so these failing tests should not be occurring, accuse they are the same as the main branch.
The failing tests seems to change with each push if that helps (e.g. right now it is failing menubar, tests, but a previous push it was failing on lablist example).

**Comment by a11ydoer** [comment]
> +1
> Looks good! It's nice to have the HTML techniques up-front.
> This is such a great example!
> 
> Preview link: https://raw.githack.com/w3c/aria-practices/update-landmark-example/examples/landmarks/
> 
> Happened to notice one tiny nit (doesn't hold up merging): The correct spelling of VoiceOver does not have a space between Voice and Over. I can open a new issue for that if you like.


This Landmark example is one of best APG examples so I used it whenever I need to explain about what Landmark is.

**Comment by spectranaut** [comment]
@jongund, you are right that the changes in this PR have not effect the regression tests. I re-ran the tests (the way we discussed in our meeting) and the tests pass now. In the future, if tests fail on the CI that do not fail locally or obviously have nothing to do with the changes in your PR, can you try re-running the failing job? I'll be working on making the test less flaky in the mean time!

**Comment by jongund** [comment]
@spectranaut 

Thanks for the help today and the information on how to restart the regression tests if they fail.

**Comment by mcking65** [comment]
@jongund thank you for this enhancement. Good step forward.

**Pull request merged**
