### PR TITLE
Issue 752: Add role, state, and property useage indexes to appendix

### PR DESCRIPTION
**Pull request by jongund**
Matt,

I created a utility to generate a table of examples based on roles and another table of examples based on properties and states.   It seems this is something that would be useful in the authoring practices as an appendix or section in the document.    The example-index.js script generates example-index.html that contains the two tables.  I created an issue for this feature and it modified the package information by added a package called "Glob".

Let me know what you think.

***
<a href="https://pr-preview.s3.amazonaws.com/jongund/aria-practices/pull/753.html" title="Last updated on Nov 25, 2018, 12:45 AM GMT (5ad0a83)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/aria-practices/753/c1211d6...jongund:5ad0a83.html" title="Last updated on Nov 25, 2018, 12:45 AM GMT (5ad0a83)">Diff</a>

### CODE REVIEW

**Comment by jongund** [comment]
I updated the pull request to automatically add an appendix to the practices with two tables, one for for listing examples by roles, and the other for listing examples by properties and states.

**Comment by mcking65** [comment]
@jongund, this looks like a fabulous start ...it's going to be super helpful to our readers. But, I don't think we can finish it up in time to land it in release 2. I changed the base branch to be a feature branch. Before we can merge, there are some conflicts that need to be resolved.

**Comment by jongund** [comment]
I fixed the validation error.  I think it is simple enough that I hope we could get it into this next version, since it is just informative information and something users have been asking about.

**Comment by mcking65** [comment]
Closing as superseded by #947. @jongund, please correct me if not so.

**Pull request closed without merging**
