### PR TITLE
fix: Broken CSS links and anchor tags

### PR DESCRIPTION
**Pull request by nschonni**
Was tring to figure out a link checker solution. Didn't find anything yet, but one did flag thesee (along with the ones @spectranaut is fixing in #1530)

***
<a href="https://pr-preview.s3.amazonaws.com/nschonni/aria-practices/pull/1535.html" title="Last updated on Sep 29, 2020, 3:19 PM UTC (556247b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/aria-practices/1535/2233e5c...nschonni:556247b.html" title="Last updated on Sep 29, 2020, 3:19 PM UTC (556247b)">Diff</a>

### CODE REVIEW

**Review by carmacleod — APPROVED** [review]
+1

Nice! I verified that all links were broken, and this PR fixes them.

Just curious - what was the name of that link checker? Seems to work... 😄

**Comment by nschonni** [comment]
https://github.com/JustinBeckwith/linkinator/
I might submit something with it later, but the CLI doesn't seem great. I had to create an index.html page and link to the files in order for it to really pick up the changes. I'll take a look at a CI action after this and the other carosel one lands with a hacky approach of renaming aria-practices to index.html 😆

**Comment by mcking65** [comment]
@nschonni Oops, just did another merge that outdated your rebase.


BTW, I've had it on the list for a long time to rename aria-practices.html to index.html, but have waited for a non-disruptive time to do it. I'd like to do it just after we publish 1.2. That's mainly because I'm not clear on what rename will do to the history, and we use the history to generate our detailed change log for the wiki.

**Comment by nschonni** [comment]
@mcking65 no worries, just rebase them all again for whichever you want to go with.

I think you can still still see the full history with the `--follow` flag https://stackoverflow.com/a/2314757/455535 but GitHub won't show anything in the blame.

I'd also suggest getting rid of aria-practices-DeletedSectionsArchive.html if you're cleaning up

**Comment by carmacleod** [comment]
> I'd also suggest getting rid of `aria-practices-DeletedSectionsArchive.html` if you're cleaning up

Please don't get rid of the Deleted Sections Archive. It contains valuable historical context. There's nowhere else that still has info on the [Rich Text Editor pattern](https://rawgit.com/w3c/aria-practices/master/aria-practices-DeletedSectionsArchive.html#richtext), for example, and its discussion about using Ctrl + M to allow tabbing out of the editor widget. 😄

**Comment by mcking65** [comment]
@carmacleod 
> Please don't get rid of the Deleted Sections Archive. It contains valuable historical context. There's nowhere else that still has info on the [Rich Text Editor pattern](https://rawgit.com/w3c/aria-practices/master/aria-practices-DeletedSectionsArchive.html#richtext), for example, and its discussion about using Ctrl + M to allow tabbing out of the editor widget. 😄


If there is anything valuable remaining, we should find a way to harvest it. I do tink we should eliminate it soon ... it is more of a problem than a help.

**Comment by nschonni** [comment]
@carmacleod @mcking65 pulled out the deletion conversation to https://github.com/w3c/aria-practices/issues/1545

**Pull request merged**
