### PR TITLE
Add Stylelint

### PR DESCRIPTION
**Pull request by sh0ji**
This adds [stylelint](https://stylelint.io/) to help us enforce the CSS style guide. Addresses #932.

Note that I chose to extend [stylelint-config-standard](https://github.com/stylelint/stylelint-config-standard) rather than implementing our own style guide. After going through [the CSS code guide](https://github.com/w3c/aria-practices/wiki/Code-Guide#css-1) to see what [stylelint rules](https://stylelint.io/user-guide/rules/) I would need to implement, it became apparent that a lot of them matched with config-standard's opinions. I also vastly prefer the idea of outsourcing code style to other configurations since it's unlikely that we'll ever spend a ton of time maintaining it.

If this seems like a reasonable approach, I'll run `stylelint --fix` to fix any existing issues in our stylesheets before merging. I haven't done that yet to avoid cluttering the list of changes.

***
<a href="https://pr-preview.s3.amazonaws.com/sh0ji/aria-practices/pull/946.html" title="Last updated on Jan 28, 2019, 11:55 PM UTC (c59129e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/aria-practices/946/0f32611...sh0ji:c59129e.html" title="Last updated on Jan 28, 2019, 11:55 PM UTC (c59129e)">Diff</a>

### CODE REVIEW

**Comment by sh0ji** [comment]
As part of this, I also added [husky](https://github.com/typicode/husky) and [lint-staged](https://github.com/okonet/lint-staged), and configured them so that when a user tries make a commit, any staged `.css` or `.js` files will be linted and fixed if errors are found. The goal of this is to reduce the contributor overhead that would be introduced by having to run the linting commands before we accept the changes.

**Comment by mcking65** [comment]
@sh0ji, I love this ... more super helpful automation improving the quality of our code base! 

My only concern is timing. Right now, we have several very active feature branches that we plan to merge to master in the next few weeks. If we do a bunch of repairs in master, we are likely to get piles of merge conflicts when we either merge those format fixes into the feature branches or when we are merging the feature branches into master. It will probably be more manageable when we are closer to release or just after release.

On the other hand, if nearly all the fixing is automatic, we could just run the auto-fixing in both master and in the feature branches. Then, it'd probably go pretty smoothly.

Thoughts?

**Comment by nschonni** [comment]
Great idea, you'll need to ignore the "common" folder since that comes from https://github.com/w3c/aria-common

**Comment by sh0ji** [comment]
@nschonni good point. I added .stylelintignore.

@mcking65, there are a fair number of issues that can't be auto-fixed. I'd propose that we fix them all as part of this MR so that master is clean. Feature branches would then need to rebase before merging, but that would be a one-time ask.

Alternatively, since #856 is still waiting, we could potentially address these issues together in a separate devops branch where we could experiment on this stuff (and potentially other things) without having to worry about master until it's all ready.

**Comment by sh0ji** [comment]
I rebased and ran `stylelint --fix`, and then manually fixed all remaining issues to see what kind of ask that would be. It was pretty straight-forward. The automatic fixes are all in b552069db6dabc00ade37b6b19dccffd71845763, while the manual fixes are all in 43a5321418813372de33a8efdb5cfd5120beb25b.

**Comment by sh0ji** [comment]
@mcking65, this should be ready for review. Here's a list of the changes since my last push:

* rebased to master and fixed issues in toolbar & carousel since they're new since I first opened this.*
* updated/rewrote the readme section on code conformance: https://github.com/sh0ji/aria-practices/tree/stylelint#code-conformance
* standardized the linting scripts as `lint:<lang>`, so `npm run lint:html` will now just run the `vnu-jar` script as you might expect
* updated the primary `fix` and `lint` scripts to just run the other scripts in sequence

This touches a lot of CSS files, but nearly every change is just to conform to stylelint's rules. There was one exception:

* the "border" property was duplicated in toolbar.css on [line 2](https://github.com/w3c/aria-practices/blob/master/examples/toolbar/css/toolbar.css#L2) and [line 8](https://github.com/w3c/aria-practices/blob/master/examples/toolbar/css/toolbar.css#L8), but with different values. I chose the line 8 version since it made the most sense to me and is the border being rendered by browsers.

**Comment by sh0ji** [comment]
Closing this to redo the PR off of a fresh master branch.

**Pull request closed without merging**
