### PR TITLE
Menu button pattern and 4 examples: Set aria-expanded to false when menus are closed

### LINKED ISSUE #697: Discuss removing recommendation in menubutton pattern to add/remove aria-expanded="true
For menu buttons and menu bars there is a different treatment of aria-expanded. 
For the [menu button](https://www.w3.org/TR/wai-aria-practices-1.1/examples/menu-button/menu-button-links.html), there is no aria-expanded on page load and then only added when it's open. So it doesn't toggle between true and false ... instead the entire attribute is added and removed.  This apparently is to [reduce chattiness](https://github.com/w3c/aria-practices/issues/326#issuecomment-295584897)

This process of adding and removing the entire attribute on expand/collapse has spotty support in JAWS, VO and NVDA. It is also tough to explain to devs... They will ask why add and remove the entire attribute when there is true/false to toggle in aria-expanded. 

On the other hand, the [navigation menu](https://www.w3.org/TR/wai-aria-practices-1.1/examples/menubar/menubar-1/menubar-1.html) has aria-expanded=false on page load. So the two examples are inconsistent.  

 It seems like we could have a more elegant and consistent solution for aria-expanded on menus. 

Maybe I should file a but against aria-haspop over on the aria 1.1 to allow an extra attribute to swap out for menus so it doesn't have the redundancy but doesn't require the clunky adding and removing the full attribute to show expanded state.... 

Or maybe AT should not announce collapsed when an aria-popup is present??

Anyway, adding removing the entire attribute and value on show/hide smells like a hack to address AT issues, or to overcome a limitation of wai-aria.  

This is the current pertinent  language in the button example:

> "Added when the menu is open.Indicates that the menu is displayed and that activating the menu button closes the menu. The aria-expanded attribute is removed when the menu is closed. Included to support touch devices where screen reader users can touch the menu button when the menu is displayed. Keyboard users cannot focus the menu button when the menu is open.

### LINKED ISSUE #2834: Revise menu button examples to declare aria-expanded="false" when collapsed
Update the JavaScript, documentation, and regression tests  for the three menubutton examples to support declaring `aria-expanded=false` when the menus are not visible.

Related to #2808 and #697.

### PR DESCRIPTION
**Pull request by andreancardona**
Closes #697 and #2834 with the following changes:
* Revise menu button pattern to specify that aria-expanded is set to false when the menu is not displayed.
* Revise JS and documentation for 3 menu button examples and the toolbar example to set aria-expanded false when their menus are closed.
* Adjusts corresponding regression tests to ensure the state of expanded is true when the menus are open and false when the menus are closed.

#### Preview links

* [Menu Button Pattern](https://deploy-preview-272--aria-practices.netlify.app/aria/apg/patterns/menu-button/)
* [Actions Menu Button Example Using aria-activedescendant](https://deploy-preview-272--aria-practices.netlify.app/aria/apg/patterns/menu-button/examples/menu-button-actions-active-descendant/)
* [Actions Menu Button Example Using <code>element.focus()</code>](https://deploy-preview-272--aria-practices.netlify.app/aria/apg/patterns/menu-button/examples/menu-button-actions/)
* [Navigation Menu Button Example](https://deploy-preview-272--aria-practices.netlify.app/aria/apg/patterns/menu-button/examples/menu-button-links/)
* [Toolbar Example](https://deploy-preview-272--aria-practices.netlify.app/aria/apg/patterns/toolbar/examples/toolbar/)

### Review checklist

*Reviewers:* To learn what needs to be covered by each review, Follow the link for the type of review to which you are assigned.

* [x] [Editorial review](https://github.com/w3c/aria-practices/wiki/Pull-Request-Review-Process#editorial_review) by @mcking65
* [x] [Functional review](https://github.com/w3c/aria-practices/wiki/Pull-Request-Review-Process#functional_review) by @mcking65
* N/A: [Visual design review](https://github.com/w3c/aria-practices/wiki/Pull-Request-Review-Process#design_review) by reviewer_id
* N/A: [Accessibility review](https://github.com/w3c/aria-practices/wiki/Pull-Request-Review-Process#accessibility_review) by reviewer_id
* [x] [Code review](https://github.com/w3c/aria-practices/wiki/Pull-Request-Review-Process#code_review) by @jongund 
* [x] [Test review](https://github.com/w3c/aria-practices/wiki/Pull-Request-Review-Process#test_review) by @a11ydoer

___
[WAI Preview Link](https://deploy-preview-272--aria-practices.netlify.app/ARIA/apg) _(Last built on Mon, 11 Dec 2023 15:40:06 GMT)._

### CODE REVIEW

**Comment by mcking65** [comment]
@andreancardona 

I don't see any javascript changes. The menubuttons do not have aria-expanded set to false when the menus are not visible.

**Comment by a11ydoer** [comment]
Regarding the test review, below example tests are missing for menu-button

- menu-button/examples/menu-button-actions-active-descendant.html:
   - menu-up-arrow
   - menu-down-arrow
   - menu-home
   - menu-character
- menu-button/examples/menu-button-links.html:
   - menu-enter

**Review by mcking65 — CHANGES_REQUESTED** [review]
@andreancardona 

It appears we still need additional changes.

content/patterns/toolbar/examples/js/FontMenuButton.js is still removing aria-expanded=false.

The tests are still testing to ensure false is not present when the menu is closed.For example, see line 88 in 
test/tests/menu-button_actions-active-descendant.js

Corresponding changes are needed in:
test/tests/menu-button_actions.js
test/tests/menu-button_links.js
test/tests/toolbar_toolbar.js

**Comment by jongund** [comment]
@andreancardona 

The following 2 tests should replace the current `toolbar-menubutton-aria-expanded` test case.
1. There is a new separate test for the `toolbar-menubutton-aria-expanded-false` case.
2. The `toolbar-menubutton-aria-expanded` case is a slightly modified version of what you currently have, it removes the test for `aria-expanded` attribute does not exist and then tests for 'true' when the menu is opened after the click function. 

Let me know if this helps,
Jon

```
ariaTest(
  'Font family button has aria-expanded=false',
  exampleFile,
  'toolbar-menubutton-aria-expanded-false',
  async (t) => {
    await assertAttributeValues(
      t,
      ex.fontFamilyButtonSelector,
      'aria-expanded',
      'false'
    );
  }
);

ariaTest(
  'Font family button has aria-expanded=true',
  exampleFile,
  'toolbar-menubutton-aria-expanded',
  async (t) => {
    await (
      await t.context.session.findElement(By.css(ex.fontFamilyButtonSelector))
    ).click();

    await assertAttributeValues(
      t,
      ex.fontFamilyButtonSelector,
      'aria-expanded',
      'true'
    );
  }
);
```

**Comment by andreancardona** [comment]
> when `aria-expanded` is true to be consist

@jongund just implemented those changes - thank you so much!

**Review by mcking65 — APPROVED** [review]
Editorial and functional reviews are complete and look good.

**Comment by mcking65** [comment]
Thank you @andreancardona for all your work on this update!

Thank you also to @jongund for the excellent support to help get this over the line.

**Pull request merged**
