### PR TITLE
Treeview examples: fix blink on hover for issue #712

### PR DESCRIPTION
**Pull request by aristov**
Fix a disgusting blinking effect appearing on hover to the right of a treeitem.

### CODE REVIEW

**Comment by aristov** [comment]
I use Chrome Version 66 on Mac OS X.
Go to [the example page](https://www.w3.org/TR/wai-aria-practices-1.1/examples/treeview/treeview-2/treeview-2a.html) and place a cursor to the right of [the Treeview widget](https://www.w3.org/TR/wai-aria-practices-1.1/examples/treeview/treeview-2/treeview-2a.html#ex1).
All treeitems have 100% width, but on hover they become highlighted their width become 16em. Since their width becomes less they become not hovered and 100% width again. This process cycles and I see blinking effect, which looks buggy.

**Comment by sh0ji** [comment]
I brought up this issue a while back in https://github.com/w3c/aria-practices/issues/225#issuecomment-351110621.

This looks good to me, but it's also happening in [treeview-1](http://w3c.github.io/aria-practices/examples/treeview/treeview-1/treeview-1a.html). @aristov, would you mind adding this fix to that example as well?

**Comment by mcking65** [comment]
@sh0ji, thanks for taking a look. 

The css change looks straight forward. But, given this is purely visual, I'm going to rely on the sightee judgments here. Did you also verify in Firefox or Safari, or in any Win browsers?

**Comment by sh0ji** [comment]
I tested this in Chrome, Firefox, and Safari on Mac, but haven't had a chance to check on Windows. The blinking issue was more prevalent in Chrome, and this fixes it in all three.

**Comment by aristov** [comment]
Done.

**Comment by mcking65** [comment]
@aristov, thank you, thank you for this contribution!

**Pull request merged**
