### PR TITLE
Color PIcker Slider update

### PR DESCRIPTION
**Pull request by jongund**
Updates to slider-1 example:
* Updated to use latest coding practices and single prototype, including use of `event.key`.
* Added touch support with increment and decrement buttons, that have been removed from tab order
* Using SVG techniques to support OS high contrast settings

[Preview](https://raw.githack.com/AnishaGubba/aria-practices/slider-1-svg/examples/slider/color-picker-sliders.html)

### CODE REVIEW

**Comment by jongund** [comment]
@spectranaut 

How do I restart the regression tests for this pull request?
The testing never seems to end and no links to restart the tests.

**Comment by spectranaut** [comment]
Hmm... maybe this is a bug in travis? If you click through to each of the checks, you can see them pass or fail -- only the summary page says "in progress".

**Comment by jongund** [comment]
I merged master into this branch and now  everything Seems to be passing.

**Comment by jongund** [comment]
Will do a pull request based on a clone rather than a fork.  My understanding it is more difficult to merge from forks, than  from clones.

**Pull request closed without merging**
