### PR TITLE
Issue 458: Auto rotating image carousel example

### PR DESCRIPTION
**Pull request by jongund**
Initial implementation of an auto rotating image carousel example

***
<a href="https://pr-preview.s3.amazonaws.com/jongund/aria-practices/pull/828.html" title="Last updated on Aug 16, 2018, 9:15 PM GMT (01fd42f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/aria-practices/828/74887d9...jongund:01fd42f.html" title="Last updated on Aug 16, 2018, 9:15 PM GMT (01fd42f)">Diff</a>

### CODE REVIEW

**Comment by jnurthen** [comment]
@jongund I think something has gone wrong here

**Comment by accdc** [comment]
Just to follow up with our discussion
https://www.w3.org/2018/08/13-aria-apg-minutes.html

Personally, I think using interactive form controls such as ARIA Tabs or Listboxes and the like is overkill for carousels, and that a standard Button role is simpler and provides all of the same functionality without forcing screen reader users into and out of Browse/Virtual cursor and Forms/Applications cursor modes when attempting to interact with it.

This is important for variable scenarios when the carousel paradigm may be used to represent interactive regions such as those including links and buttons, or structural content such as headings, images, and tables, or when even representing simulated wizard constructs consisting of sequential forms.

Also, if what was suggested during the call is done, where when the focused Tab is activated focus moves to the slide container, this breaks the ARIA Tab paradigm where focus is not supposed to be moved away from selected tabs when activated, which will end up being just another case of hacking something that isn't meant to be used for such a purpose and breaking it slightly to do something else.

**Comment by mcking65** [comment]
Closing ... looks like something went terribly wrong ... every file in the repo is changed and irrelevant changes are overwheling the PR. Please resubmit a clean PR based on the current state of the carousel branch in the w3c/aria-practices repo.

**Comment by mcking65** [comment]
I'm going to re-open this and give another try now that I have updated the base branch.

**Comment by mcking65** [comment]
@jongund, there are HTML validation errors in the example page. I'm going to go ahead and merge into the w3c/aria-practices@carousel branch. But, please either fix these directly in the carousel branch or in a PR based on the latest state of the carousel branch in w3c/aria-practices.

**Pull request merged**
