### PR TITLE
Stop gh-pages deploy for Repo Restructure Project issue 2419

### PR DESCRIPTION
**Pull request by alflennik**
Stops the automatic deployment to GitHub Pages which currently occurs when new commits are pushed to the main branch. Note that the build will fail until the changes on the `move-examples-6` branch (https://github.com/w3c/aria-practices/pull/2441) are approved and merged.

### CODE REVIEW

**Review by howard-e — APPROVED** [review]

**Comment by mcking65** [comment]
@alflennik 

What do you think of using main as the base branch for this PR instead of move-examples? Then we could start building changes to the gh-pages branch to replace the editor's draft with redirects in a separate branch that is independent of #2417.

I'm thinking of following order of operations:
1. Turn off build of editor's draft in gh-pages from aria-practices.html with this PR
2. Branch gh-pages and make PR to merge to gh-pages, changing its content to redirect readers to new site on wai site
3. Merge 2417 with new content tree into main

With that order, we can then safely remove content from aria-practices.html as part of 2417.

Thoughts?

**Comment by nschonni** [comment]
Someone with permissions can also disable the job from https://github.com/w3c/aria-practices/actions/workflows/deploy.yml. There is a "Disable Workflow" option in the `...` menu of that page

**Comment by mcking65** [comment]
@nschonni 

Thanks for the tip. I disabled it.

@alflennik 

I think we could just do this delete in main. Let me know what you think.

**Comment by alflennik** [comment]
@mcking65 Ok I changed the base branch to main. If you approve, go ahead and merge since I don't have merge access to protected branches.

**Pull request merged**
