### PR TITLE
All Example Pages: Add source copy instructions and CodePen button to HTML source section

### PR DESCRIPTION
**Pull request by ariellalgilmore**
Resolve issue #3027 with the following changes:
1. Direct readers to copy HTML source from codepen instead of from the example page.
2. Add an additional codepen button adjacent to the directions.

#### Preview

[Preview revised combobox example page in compare branch](https://deploy-preview-328--aria-practices.netlify.app/aria/apg/patterns/combobox/examples/combobox-autocomplete-list/)

### Review checklist

*Reviewers:* To learn what needs to be covered by each review, Follow the link for the type of review to which you are assigned.

* [ ] [Editorial review](https://github.com/w3c/aria-practices/wiki/Pull-Request-Review-Process#editorial_review) by @mcking65 
* [x] [Visual design review](https://github.com/w3c/aria-practices/wiki/Pull-Request-Review-Process#design_review) by @a11ydoer and @curtbellew 
* [ ] [Functional review](https://github.com/w3c/aria-practices/wiki/Pull-Request-Review-Process#functional_review) by @mcking65
* [ ] [Code review](https://github.com/w3c/aria-practices/wiki/Pull-Request-Review-Process#code_review) by reviewer_id (
* N/A: [Accessibility review](https://github.com/w3c/aria-practices/wiki/Pull-Request-Review-Process#accessibility_review) by reviewer_id
* N/A: [Test review](https://github.com/w3c/aria-practices/wiki/Pull-Request-Review-Process#test_review) by reviewer_id

___
[WAI Preview Link](https://deploy-preview-328--aria-practices.netlify.app/ARIA/apg) _(Last built on Tue, 23 Jul 2024 14:44:48 GMT)._

### CODE REVIEW

**Comment by ariellalgilmore** [comment]
@mcking65 this is not ideal code, but I tweaked some files and updated, so that the deploy preview now shows the open in codePen button inside the HTML source code section for this example only! Just wanted to get some feedback first before making more permenent changes

**Comment by mcking65** [comment]
I made some changes. My understanding of the discussion is that we keep the display but just make the changes I described in the revised top comment in this PR.

I'd like to suggest just one modification to the DOM order. Currently the open in codepen button in the HTML source section is appearing after the screen reader separator `<div role="separator"...`. It would be better if it were placed between the paragraph and the separator like in the example section where the button is between the heading and the separator.

**Comment by a11ydoer** [comment]
@mcking65 @curtbellew I did QA for "open in codepen" for HTML source section. Everything looks good!

**Review by a11ydoer — APPROVED** [review]
This is approved!

**Comment by ariellalgilmore** [comment]
Thanks @curtbellew ! I fixed to confirm all example pages with multiple examples should be working now

**Comment by mcking65** [comment]
@ariellalgilmore 

I just checked the [preview of Example Listboxes with Rearrangeable Options | APG | WAI | W3C](https://deploy-preview-328--aria-practices.netlify.app/aria/apg/patterns/listbox/examples/listbox-rearrangeable/#htmlsourcecode). All the codepen buttons except for one work correctly. The one that produces an empty codepen is the codepen button for the HTML source section for example 1 that @curtbellew  mentioned.

screenshot of codepen button


screenshot of empty codepen

**Comment by ariellalgilmore** [comment]
Hi @mcking65 i just retriggered the deploy preview and the codepen should be working now: https://deploy-preview-328--aria-practices.netlify.app/aria/apg/patterns/listbox/examples/listbox-rearrangeable/#htmlsourcecode. 

Screenshot 2024-07-23 at 7 55 03 AM

**Review by curtbellew — APPROVED** [review]
Looks great!

**Comment by mcking65** [comment]
Thank you @ariellalgilmore  for all your work on this! Once again, it turned into something bigger than anticipated and you rose to the occasion!

Thank you also to @curtbellew  and @a11ydoer  for your help reviewing all the pages effected!

**Pull request merged**
