### PR TITLE
carousel Example with buttons for slide control: Improve High Contrast Support and implementation of APG Programming Practices

### PR DESCRIPTION
**Pull request by jongund**
This pull request updates the current carousel example with previous and next buttons:

1. Provide view options similar to the tabbed carousel example
1. Improved color contrast support
1. Improved keyboard focus styling
1. Updated JS to new example design patterns
1. Updated documentation

### Preview Link

[Preview updated carousel in compare branch](https://raw.githack.com/w3c/aria-practices/update-carousel-previous-next/examples/carousel/carousel-1-prev-next.html?)

### Review checklist

* [x] [Editorial review](https://github.com/w3c/aria-practices/wiki/Pull-Request-Review-Process#editorial_review) by @mcking65
* [x] [Functional review](https://github.com/w3c/aria-practices/wiki/Pull-Request-Review-Process#functional_review) by @carmacleod 
* [x] [Visual design review](https://github.com/w3c/aria-practices/wiki/Pull-Request-Review-Process#design_review) by @a11ydoer
* [x] [Accessibility review](https://github.com/w3c/aria-practices/wiki/Pull-Request-Review-Process#accessibility_review) by @charmarkk
* [x] [Code review](https://github.com/w3c/aria-practices/wiki/Pull-Request-Review-Process#code_review) by @spectranaut (NOTE: there is a new requirement in the [code review process](https://github.com/w3c/aria-practices/wiki/Pull-Request-Review-Process#code-review))
* [x] [Test review](https://github.com/w3c/aria-practices/wiki/Pull-Request-Review-Process#test_review) by @spectranaut

### CODE REVIEW

**Comment by a11ydoer** [comment]
Visual design review - When we make another version of the slider next time, I would like to recommend to change the design of the arrows, buttons for previous and next slide, to simpler ones. 
modernarrow
It would also help to prevent the strecthy look of buttons.

**Comment by carmacleod** [comment]
Sorry, @jongund - I meant to create a PR against your branch, but I messed up and pushed directly to your branch.
It was only editorial nits, like a space before a comma, and a space between "be come" instead of "become" (plus a few more nits).
I just recently changed from having my own fork of APG to working directly from a clone of the repo, so I guess I need to figure out how to create a PR for a branch. Sorry again!

**Comment by carmacleod** [comment]
Two of the points about the rotation control button in the Accessibility Features section may need a bit of revising to match behavior.

1.
> - If a user has activated the button to stop the show, the rotation will only restart if the button is activated. Moving keyboard focus or the mouse out of the carousel will not restart rotation.

This is correct, but we may want to add a new point describing the opposite behavior, because it might not be intuitive:
> - If a user has activated the button to start the show, the rotation will only stop if the button is activated again. Moving keyboard focus or the mouse into the carousel will not stop rotation.

----
2.
> - If keyboard focus is inside the carousel, or if the mouse is hovering over the carousel, the button is disabled; it cannot be used to start rotation.

This point doesn't seem to match the current behavior. The button isn't really disabled, because it still changes from pause to play, and as soon as the mouse is moved off of the carousel, rotation starts up again.

**Comment by carmacleod** [comment]
Tested Windows HCM High Contrast White, to compliment @charmarkk's High Contrast Black test. Everything is visible in white also.

**Comment by jongund** [comment]
@carmacleod 
Thanks for catching problems in the documentation.  Made some edits to remove the issue.  No problem merging your edits in this branch.

**Comment by carmacleod** [comment]
@jongund Thanks for deleting the point about the disabled button - makes sense now.

Regarding adding a new point after:
> - If a user has activated the button to stop the rotation, the rotation will only restart if the button is activated. Moving keyboard focus or the mouse out of the carousel will not restart rotation when the button is in the stopped state.

Here's what I had in mind for the new point:
> - If a user has activated the button to **_start_** the rotation, the rotation will only **_stop_** if the button is activated again. Moving keyboard focus or the mouse **_into_** the carousel will not _**stop**_ rotation when the button _**has re-entered the playing state**_.

To see this, try the following steps:
- go to https://raw.githack.com/w3c/aria-practices/update-carousel-previous-next/examples/carousel/carousel-1-prev-next.html
- make sure none of the options are checked
- refresh the page, to clear any previous state
- with the mouse, click the pause button (the button takes focus, and the rotation stops)
- hover the mouse over the slide and leave it there
- with the keyboard, type enter or space to activate the play button
   - the rotation starts, and keeps going, even though the mouse is still over the slide
- type tab to move focus to one of the other buttons or to the slide itself
   - the rotation continues, even though focus is within the carousel

I believe we did this on purpose, because if I recall correctly, we said "if the user intentionally presses the play button again after they pressed pause, then they obviously want the carousel to rotate regardless of hover or focus". But we should explain it with the new point, because it might not be completely clear what is going on there.

**Comment by carmacleod** [comment]
> No problem merging your edits in this branch.

Phew - thanks, @jongund !
I figured out that all I need to do to create a pull request on your branch is to push to a new branch... I should've realized that!
Always learning! ;)

**Comment by carmacleod** [comment]
+1
The new rotation button point looks good, @jongund. Thanks!

**Comment by mcking65** [comment]
@jongund 
Valerie will be able to re-review this on Thursday. Otherwise, this is ready to go. So, please do not make further changes. Assuming your responses to Valerie's review are sufficient, I will merge this on Thursday afternoon.

**Review by spectranaut — APPROVED** [review]
Code review for previously requested changes: Approved! Looks great!! Thanks so much for the readability changes @jongund !

**Pull request merged**
