### PR TITLE
Editor Menubar Example: Add notes about hover and focus movement

### PR DESCRIPTION
**Pull request by mcking65**
For issue #603, modified: examples/menubar/menubar-2/menubar-2.html.
In the accessibility features section, added items 4 and 5 describing the conditions when mouse hover can move focus.

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/aria-practices/pull/711.html" title="Last updated on Jun 27, 2018, 7:07 AM GMT (2d297b6)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/aria-practices/711/c555c83...2d297b6.html" title="Last updated on Jun 27, 2018, 7:07 AM GMT (2d297b6)">Diff</a>

### CODE REVIEW

**Comment by mcking65** [comment]
@annabbott,

To preview this change, go to the [editor menubar example in the issue 603 branch](https://rawgit.com/w3c/aria-practices/issue603/examples/menubar/menubar-2/menubar-2.html) and scroll down to the "Accessibility Features" section under the example. This change adds items 4 and 5 to the list in that section. Please review the wording in those items. You can leave a comment here or on the files tab of this pull request where you can see the HTML for tyhe changes.

**Comment by mcking65** [comment]
Well, stackoverflow suggested I could clean up the commit list for the PR by changing the base branch to another branch and then changing back ... no such luck. I'm not going to bother creating a new PR just because of a rebase to bring this branch up to date. There is only one file change in this branch that is not in master ... the one in the menubar2 html file. The other 10 commits that are showing up in the commit list are already in master. They only got into this PR when I rebased the branch on top of master to make sure the latest changes to editor menubar would merged cleanly with this one. Sometimes github is not optimal.

**Comment by annabbott** [comment]
"Accessibility Features" > items 4 and 5 look good.
Found one nit: "Accessibility Features" > item 2: remove extra space after last word of sentence and the period.
Also added this comment to #603 (instructions were confusing).

**Comment by mcking65** [comment]
@annabbott, thanks for the review. I removed the extra space.

**Pull request merged**
