### PR TITLE
Infrastructure: Fix previously excluded ESLint issues

### PR DESCRIPTION
**Pull request by nschonni**
Built off of #1602, then when through and addressed the missing/undefined variable issues by example

### CODE REVIEW

**Comment by nschonni** [comment]
@jongund even if this doesn't land, there might be a few bits to apply to your in-progress PRs

**Review by spectranaut — APPROVED** [review]
I'm in favor of this change and it all looks good, thanks so much to getting to this work, @nschonni. Just curious, did you use a tool to clean these up?

**Comment by nschonni** [comment]
I don't think much of this was auto-fixable. I think I probably just manually cleaned it up while I was trying to distract my brain

**Comment by spectranaut** [comment]
@nschonni If there was a tool I wanted to know about it :) I really appreciate the work!

**Comment by mcking65** [comment]
@nschonni 
Sorry, think #1623 resulted in conflicts. When you get a chance, could you please rebase?

**Comment by nschonni** [comment]
@mcking65 no problem, it was based on that other PR, but I guess got out of sync. I've rebased this one now

**Comment by mcking65** [comment]
@nschonni 
I should have merged right after you last rebased ... sorry. So, I updated the branch and surprised to see some failing tests.

**Comment by mcking65** [comment]
@nschonni 
Just after merging this, regression started failing again for the spinbutton increment/decrement tests in  #1712. I don't understand how that is possible since that testing passed for this PR. Maybe unrelated? Maybe related? Confused.

**Comment by nschonni** [comment]
Not related to this, I think it's hitting another issue related to the new year. EX: it also failed on PRs yesterday https://github.com/w3c/aria-practices/runs/1661714101?check_suite_focus=true

**Comment by nschonni** [comment]
I fixed it in https://github.com/w3c/aria-practices/pull/1640/commits/e4e0cf79ad3065018c114ca3b2cd52f1d487a6aa as part of the larger https://github.com/w3c/aria-practices/pull/1640, but I can split that out if you want a quicker PR to get stuff green again

**Pull request merged**
