### PR TITLE
Grid examples and Feed Display: Rename html files to remove camel casing

### PR DESCRIPTION
**Pull request by alflennik**
There are a few pages in the APG which have capitalizations in their URLs, which can cause issues especially with Netlify which automatically lowercases all URLs. This PR updates the advanced-data-grid, layout-grids and data-grids pages as well as the feed-display page to use train-case instead of camelCase.

Part of fix for w3c/wai-aria-practices#192.

Should not be merged until PR https://github.com/w3c/wai-aria-practices/pull/187 is merged.
___
WAI Preview Link [failed to build](https://github.com/w3c/wai-aria-practices/runs/11047091452?check_suite_focus=true) on 'Update site files' step. _(Last tried on Wed, 01 Feb 2023 22:25:33 GMT)._

### CODE REVIEW

**Comment by alflennik** [comment]
Failed link checker is caused by an external page experiencing some downtime.

**Comment by alflennik** [comment]
Preview is here: https://deploy-preview-188--aria-practices.netlify.app/aria/apg/patterns/feed/examples/feed/

The current version of wai-aria-practices does not support the feed-display name changes, support for that will be in https://github.com/w3c/wai-aria-practices/issues/186, so that change will not be reflected in the preview.

**Comment by mcking65** [comment]
@alflennik pls let me know when this is ready for merge by sending email directly to my Meta email.

**Comment by alflennik** [comment]
@mcking65 This PR is not included in the https://github.com/w3c/wai-aria-practices/pull/189 release because I found that it was not needed to fix the 404s, and there is still an issue with the preview build for this PR that I have not solved yet. I'll let you know when it's ready to review and we can try to get it out in next week's release.

**Review by mcking65 — APPROVED** [review]
@alflennik thank you, looks good.

**Pull request merged**
