### PR TITLE
Fix links to Carousel Example with Buttons for Slide Control

### PR DESCRIPTION
**Pull request by spectranaut**
I  just notice the link to [the first carousel example](https://w3c.github.io/aria-practices/#carousel) is broken in master:

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/aria-practices/pull/1530.html" title="Last updated on Sep 30, 2020, 5:36 PM UTC (671f5dd)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/aria-practices/1530/9d19d94...671f5dd.html" title="Last updated on Sep 30, 2020, 5:36 PM UTC (671f5dd)">Diff</a>

### CODE REVIEW

**Comment by carmacleod** [comment]
Thanks @spectranaut !
The link to carousel 1 seems to be broken on the [second example page](https://w3c.github.io/aria-practices/examples/carousel/carousel-2-tablist.html) as well. Same fix needed there, too. :)

**Comment by spectranaut** [comment]
done @carmacleod thx! :)

**Comment by nschonni** [comment]
I think the same issue is fixed for the 3rd example page with https://github.com/w3c/aria-practices/pull/1524 😄

**Comment by carmacleod** [comment]
@nschonni 
> I think the same issue is fixed for the 3rd example page with #1524 😄

The fixes in this PR are in aria-practices.html and examples/carousel/carousel-2-tablist.html,
but the fixes in #1524 are in examples/index.html.

Does the script that generates examples/index.html (reference-tables.js, I believe?) run automatically?
If not, maybe it could now?

**Comment by nschonni** [comment]
Sorry, I was just trying to say I think it's broken in a third place 😆 

#1524 would make it run automatically, and also add a local commit hook as well, but I don't want to derail this PR thread

**Comment by carmacleod** [comment]
Ohhh! Sorry! Now that I read your sentence more carefully, I totally get what you were saying. Oops! 😳 

And thanks for the reply about running automatically - I should have read the comment in #1524 instead of just jumping to the Files changed tab to look for the broken link fix.

**Review by carmacleod — APPROVED** [review]
+1

This PR is good to go.
Thanks, @spectranaut !

**Pull request merged**
