### PR TITLE
Combobox Date Picker Example: Change previous and next month and year behavior for dates near end of month

### PR DESCRIPTION
**Pull request by jongund**
Provides partial resolution of #2581.
The remainder of the resolution is provided by #2643.

This PR changes behavior of commands for next and previous month and year In the combobox date picker when the currently focused date does not exist in the previous or next month or year. With these changes, if the same day number does not exist in the newly displayed month, the last day of the newly displayed month receives focus.

[Preview of revised combobox date picker example in Netlify](https://deploy-preview-194--aria-practices.netlify.app/aria/apg/patterns/combobox/examples/combobox-datepicker/).

- [x] Editorial review @mcking65 
- [x] Functional test @mcking65 
- [x] Code review @alflennik 

___
[WAI Preview Link](https://deploy-preview-194--aria-practices.netlify.app/ARIA/apg) _(Last built on Tue, 04 Apr 2023 01:43:50 GMT)._

### CODE REVIEW

**Comment by mcking65** [comment]
@jongund 

Would you like to update the keyboard documentation table, or would you like me to do that?

I am surprised we are not testing this behavior. I don't see any changes to `test/tests/combobox_datepicker.js`, yet all tests pass. Are we missing some tests?

**Review by alflennik — COMMENTED** [review]
I reviewed the functionality of the widget and I was happy to find that it worked super reliably, even with lots of code changes.

One thing I did was to build the APG website and try the widget in that context. While everything works, I did notice that the table has some styling which makes it less aesthetically pleasing than the non-website version. I do think this is a preexisting issue, but in any case below are some changes that would make the styling consistent in both contexts:

```diff
  .combobox-datepicker .dates {
      width: 320px;
      padding-left: 1em;
      padding-right: 1em;
      padding-top: 1em;
+     border-collapse: separate; /* Needed for website */
  }
```

```diff
  .combobox-datepicker .dates th, #myDatepicker .dates th {
      padding: 0;
+     /* Needed for website */
+     color: black;
+     background: transparent;
+     border: none;
  }
```

One thing I noticed is that hovering the mouse over the active date results in poor contrast, so I would suggest a change like this:

```diff
  .combobox-datepicker .dates td:hover {
    background-color: rgb(218, 231, 251);
+   color: black;
  }
```

I ran the tests and they passed. One minor issue is the fact that there is a lot of logging output coming from line 323 of the test file. I think that's a preexisting issue but it might be nice to take this opportunity to remove the noise from the test output.

**Comment by jongund** [comment]
@alflennik 
Thank you for the testing I will update the CSS based on your comments.

**Review by alflennik — APPROVED** [review]
Looks great, thanks Jon!

**Review by mcking65 — APPROVED** [review]
@jongund  All good!

I made some minor changes to the wording of the page up and down documentation that we'll want to carry forward into the date picker dialog documentation as well.

**Pull request merged**
