### PR TITLE
chore: add VNU checking

### PR DESCRIPTION
**Pull request by nschonni**
From the README:
> All HTML should validate in the NU HTML Validator. Exceptions to this rule are warnings and errors related to future ARIA features we need to implement.

Current errors are below, but may be related to current work
```console
"file:examples/landmarks/at.html":93.18-93.119: error: Bad value “80%” for attribute “width” on element “img”: Expected a digit but saw “%” instead.
"file:examples/landmarks/at.html":126.20-126.121: error: Bad value “80%” for attribute “width” on element “img”: Expected a digit but saw “%” instead.
"file:examples/landmarks/at.html":187.16-187.115: error: Bad value “80%” for attribute “width” on element “img”: Expected a digit but saw “%” instead.
"file:examples/landmarks/at.html":97.13-97.44: error: The “aria-labelledby” attribute must point to an element in the same document.
"file:examples/listbox/listbox.html":65.13-65.117: error: Bad value “” for attribute “aria-activedescendant” on element “ul”: An ID must not be the empty string.
"file:examples/listbox/listbox.html":124.13-130.42: error: Bad value “” for attribute “aria-activedescendant” on element “ul”: An ID must not be the empty string.
"file:examples/menu-button/menu-button-links.html":59.15-59.30: error: Bad value “none” for attribute “role” on element “li”.
"file:examples/menu-button/menu-button-links.html":64.15-64.30: error: Bad value “none” for attribute “role” on element “li”.
"file:examples/menu-button/menu-button-links.html":69.15-69.30: error: Bad value “none” for attribute “role” on element “li”.
"file:examples/menu-button/menu-button-links.html":74.15-74.30: error: Bad value “none” for attribute “role” on element “li”.
"file:examples/menu-button/menu-button-links.html":79.15-79.30: error: Bad value “none” for attribute “role” on element “li”.
"file:examples/menu-button/menu-button-links.html":84.15-84.30: error: Bad value “none” for attribute “role” on element “li”.
"file:examples/toolbar/toolbar.html":41.13-41.95: error: Attribute “aria-selected” not allowed on element “div” at this point.
```

To ignore work in progress the [--filterpattern](https://www.npmjs.com/package/vnu-jar#--filterpattern-pattern) option could be used till patches are landed in the validator.

/cc @sideshowbarker

### CODE REVIEW

**Comment by MichielBijl** [comment]
@nschonni could you have a look at the error log? It tries to install an aria-practices 0.0.0 package :/.

**Comment by nschonni** [comment]
`aria-practices@0.0.0` is this repo https://github.com/w3c/aria-practices/blob/master/package.json#L3

**Comment by nschonni** [comment]
Spun off some separate issues and PRs for the existing errors.
- Incorrect `width` value #427
- Incorrect labelledby value #428
- Empty aria-activedescendant #429

Not sure about the `role=none` ones. Maybe those should be filtered

**Comment by MichielBijl** [comment]
@nschonni whoop whoop! I’ll have a look at the new issues. role=none is valid per aria 1.1 so that should def be filtered.

**Comment by nschonni** [comment]
Added a filter file, but I'm not sure about this one
```console
aria-practices/examples/toolbar/toolbar.html":41.13-41.95: error: Attribute “aria-selected” not allowed on element “div” at this point.
```

**Comment by nschonni** [comment]
Rebased and opened a few new PRs to address newer markup issues

**Comment by mcking65** [comment]
After setting up a branch with these changes, I tried running npm test:

~~~
$ npm test

> aria-practices@0.0.0 test C:\Users\mck\git\APG\main
> npm run lint && npm run vnu-jar


> aria-practices@0.0.0 lint C:\Users\mck\git\APG\main
> eslint bin examples


> aria-practices@0.0.0 vnu-jar C:\Users\mck\git\APG\main
> java -jar node_modules/vnu-jar/build/dist/vnu.jar --errors-only --filterfile .vnurc --no-langdetect examples/**/*.html


mck@MCK--243 MINGW64 ~/git/APG/main (nschonni-vnu-jar)
$
~~~

Why isn't it spitting out the validation errors for me? I should find the errors with fixes proposed in PRs #537 and #538; I haven't yet merged those fixes.

BTW, after setting up this branch, I did update my NPM packages.

**Comment by nschonni** [comment]
Those fixes are independent markup errors.

Do you have Java available in that environment? Not sure if it would probably just throw a different error if you didn't.

**Comment by jnurthen** [comment]
Logged https://github.com/validator/validator/issues/579 for the rowgroup in table issue

**Comment by jnurthen** [comment]
@nschonni Can you please add to the filter the following error:
An element with “role=rowgroup” must be contained in, or owned by, an element with “role=grid”.

**Comment by nschonni** [comment]
@jnurthen added the filter for the rowgroup

The last commit could be submitted separately, but I figured I'd include it to make the build green

**Comment by nschonni** [comment]
Although #429 is closed, I couldn't remove the suppression of `Bad value “” for attribute “aria-activedescendant” on element “ul”: An ID must not be the empty string`

**Comment by nschonni** [comment]
@mcking65 is there any other changes needed for this?

**Comment by nschonni** [comment]
Bumped and rebased since some of the ignored errors have been addressed in the validator

**Comment by nschonni** [comment]
Rebased to fix conflict

**Comment by jnurthen** [comment]
Thanks. Lets see how this goes!

**Pull request merged**
