### PR TITLE
Create Dependabot config file

### LINKED ISSUE #1351: An in-range update of stylelint is breaking the build 🚨
***
☝️ **Important announcement:** Greenkeeper will be saying goodbye 👋 and passing the torch to Snyk on June 3rd, 2020! [Find out how to migrate to Snyk and more at greenkeeper.io](https://greenkeeper.io)
***
## The devDependency [stylelint](https://github.com/stylelint/stylelint) was updated from `13.2.0` to `13.2.1`.

🚨 [View failing branch](https://github.com/w3c/aria-practices/compare/master...w3c:greenkeeper%2Fstylelint-13.2.1).

This version is **covered** by your **current version range** and after updating it in your project **the build failed**.

stylelint is a devDependency of this project. It **might not break your production code or affect downstream projects**, but probably breaks your build or test tools, which may **prevent deploying or publishing**.

<details>
<summary>Status Details</summary>

- ❌ **Travis CI - Branch:** <a href='https://travis-ci.com/w3c/aria-practices/builds/152458046'> The build</a> **errored**. 
</details>

---

<details>
<summary>Release Notes for 13.2.1</summary>

<ul>
<li>Fixed: <code>selector-pseudo-element-no-unknown</code> false positives for <code>::part</code> pseudo-element (<a href="https://urls.greenkeeper.io/stylelint/stylelint/pull/4604" data-hovercard-type="pull_request" data-hovercard-url="/stylelint/stylelint/pull/4604/hovercard">#4604</a>).</li>
<li>Fixed: <code>value-keyword-case</code> false positives for longhand <code>grid-column/row-*</code> properties (<a href="https://urls.greenkeeper.io/stylelint/stylelint/pull/4611" data-hovercard-type="pull_request" data-hovercard-url="/stylelint/stylelint/pull/4611/hovercard">#4611</a>).</li>
</ul>
</details>

<details>
<summary>Commits</summary>
<p>The new version differs by 23 commits.</p>
<ul>
<li><a href="https://urls.greenkeeper.io/stylelint/stylelint/commit/7f2b65de16f8eea29686c3937abde065dd3c2302"><code>7f2b65d</code></a> <code>13.2.1</code></li>
<li><a href="https://urls.greenkeeper.io/stylelint/stylelint/commit/c52054f6b0e8f44427be7a5235daac5750429ef9"><code>c52054f</code></a> <code>Prepare 13.2.1</code></li>
<li><a href="https://urls.greenkeeper.io/stylelint/stylelint/commit/343e40dcb625e4d1001db441e4dcf7ac105784cf"><code>343e40d</code></a> <code>Bump typescript from 3.7.5 to 3.8.3 (#4626)</code></li>
<li><a href="https://urls.greenkeeper.io/stylelint/stylelint/commit/f9280582c5028d76696a3b3811abfabaaca88cdd"><code>f928058</code></a> <code>Bump postcss-value-parser from 4.0.2 to 4.0.3 (#4625)</code></li>
<li><a href="https://urls.greenkeeper.io/stylelint/stylelint/commit/08770c869ba1cc11e00b0503e5aac5e2d7a89555"><code>08770c8</code></a> <code>Bump np from 5.2.1 to 6.2.0 (#4629)</code></li>
<li><a href="https://urls.greenkeeper.io/stylelint/stylelint/commit/c63a45fbbde88010cd43703feb6591475db213ab"><code>c63a45f</code></a> <code>Bump postcss from 7.0.26 to 7.0.27 (#4628)</code></li>
<li><a href="https://urls.greenkeeper.io/stylelint/stylelint/commit/818e3ca51578f864ada5cb29593e1054806e2476"><code>818e3ca</code></a> <code>Bump got from 10.5.5 to 10.6.0 (#4632)</code></li>
<li><a href="https://urls.greenkeeper.io/stylelint/stylelint/commit/7073482f6612e61fea4ca92300424b9da5249cd0"><code>7073482</code></a> <code>Bump write-file-atomic from 3.0.1 to 3.0.3 (#4627)</code></li>
<li><a href="https://urls.greenkeeper.io/stylelint/stylelint/commit/21b5616e3e2f9a83457cad7a8e24950e09c31bc7"><code>21b5616</code></a> <code>Bump lint-staged from 10.0.7 to 10.0.8 (#4630)</code></li>
<li><a href="https://urls.greenkeeper.io/stylelint/stylelint/commit/500a7c82ae29b05c3936d8da541dc8e4af7ad068"><code>500a7c8</code></a> <code>Bump meow from 6.0.0 to 6.0.1 (#4631)</code></li>
<li><a href="https://urls.greenkeeper.io/stylelint/stylelint/commit/0254e50a7885bc3766104be6abefeb1d074a28f5"><code>0254e50</code></a> <code>Remove org-level community health files (#4612)</code></li>
<li><a href="https://urls.greenkeeper.io/stylelint/stylelint/commit/a6ae70e4cc3a0db4be557ad8e542a9546870eb48"><code>a6ae70e</code></a> <code>Reinstate issue template</code></li>
<li><a href="https://urls.greenkeeper.io/stylelint/stylelint/commit/95f71b425cc8cb99e00e57113acc4f019fdc57bc"><code>95f71b4</code></a> <code>Temporarily delete one issue template</code></li>
<li><a href="https://urls.greenkeeper.io/stylelint/stylelint/commit/3b30adaed1cb179beeb1fd97d0d6d8c8e4ea89ed"><code>3b30ada</code></a> <code>Delete PULL_REQUEST_TEMPLATE.md (#4606)</code></li>
<li><a href="https://urls.greenkeeper.io/stylelint/stylelint/commit/dfc08b978771ee32f4e22837cb5e84dc79e70136"><code>dfc08b9</code></a> <code>Update CHANGELOG.md</code></li>
</ul>
<p>There are 23 commits in total.</p>
<p>See the <a href="https://urls.greenkeeper.io/stylelint/stylelint/compare/142ed1c5e5224f47268b250ea58f1cfce7550104...7f2b65de16f8eea29686c3937abde065dd3c2302">full diff</a></p>
</details>

<details>
<summary>FAQ and help</summary>

There is a collection of [frequently asked questions](https://greenkeeper.io/faq.html). If those don’t help, you can always [ask the humans behind Greenkeeper](https://github.com/greenkeeperio/greenkeeper/issues/new).
</details>

---

Your [Greenkeeper](https://greenkeeper.io) Bot :palm_tree:

### LINKED ISSUE #1368: Convert from Greenkeeper to DependaBot
Greenkeeper is shutting down June 1st https://greenkeeper.io/
They push their clients towards Snyk, but DependaBot is the platform acquired by GitHub, and already powering the security PRs to repos.
Might want to check if there is a general w3c direction, otherwise, someone with admin on the repo can probably just go to https://dependabot.com/ to setup the hook and disable the Greenkeeper one

### LINKED ISSUE #1382: An in-range update of lint-staged is breaking the build 🚨
***
☝️ **Important announcement:** Greenkeeper will be saying goodbye 👋 and passing the torch to Snyk on June 3rd, 2020! [Find out how to migrate to Snyk and more at greenkeeper.io](https://greenkeeper.io)
***
## The devDependency [lint-staged](https://github.com/okonet/lint-staged) was updated from `10.1.4` to `10.1.5`.

🚨 [View failing branch](https://github.com/w3c/aria-practices/compare/master...w3c:greenkeeper%2Flint-staged-10.1.5).

This version is **covered** by your **current version range** and after updating it in your project **the build failed**.

lint-staged is a devDependency of this project. It **might not break your production code or affect downstream projects**, but probably breaks your build or test tools, which may **prevent deploying or publishing**.

<details>
<summary>Status Details</summary>

- ❌ **Travis CI - Branch:** <a href='https://travis-ci.com/github/w3c/aria-practices/builds/160826733'> The build</a> **failed**. 
</details>

---

<details>
<summary>Release Notes for v10.1.5</summary>

<h2><a href="https://urls.greenkeeper.io/okonet/lint-staged/compare/v10.1.4...v10.1.5">10.1.5</a> (2020-04-18)</h2>
<h3>Bug Fixes</h3>
<ul>
<li>pass correct path to unstaged patch during cleanup (<a href="https://urls.greenkeeper.io/okonet/lint-staged/commit/6066b07">6066b07</a>)</li>
</ul>
</details>

<details>
<summary>Commits</summary>
<p>The new version differs by 1 commits.</p>
<ul>
<li><a href="https://urls.greenkeeper.io/okonet/lint-staged/commit/6066b076b9cd9d836044e062a3bfdb80bf02d0a2"><code>6066b07</code></a> <code>fix: pass correct path to unstaged patch during cleanup</code></li>
</ul>
<p>See the <a href="https://urls.greenkeeper.io/okonet/lint-staged/compare/0bf1fb055bcdd455756b7df46001781adca48838...6066b076b9cd9d836044e062a3bfdb80bf02d0a2">full diff</a></p>
</details>

<details>
<summary>FAQ and help</summary>

There is a collection of [frequently asked questions](https://greenkeeper.io/faq.html). If those don’t help, you can always [ask the humans behind Greenkeeper](https://github.com/greenkeeperio/greenkeeper/issues/new).
</details>

---

Your [Greenkeeper](https://greenkeeper.io) Bot :palm_tree:

### LINKED ISSUE #1402: Migrate greenkeeper to Snyk
From #1382

>☝️ **Important announcement:** Greenkeeper will be saying goodbye 👋 and passing the torch to Snyk on June 3rd, 2020! [Find out how to migrate to Snyk and more at greenkeeper.io](https://greenkeeper.io)

### PR DESCRIPTION
**Pull request by nschonni**
Since greenkeeper is shutdown, this will enable the native dependabot PRs to this repo for new version releases of the dependencies.

Closes #1368
Closes #1402
Closes #1382
Closes #1351

### CODE REVIEW

**Comment by nschonni** [comment]
@spectranaut I think your other PR for vnu-jar will still be needed after this, since when I tested on my fork, the Dependabot PR for it was failing because of the new errors

**Review by spectranaut — APPROVED** [review]
Thanks thanks for this @nschonni! I'll be relieved to having everything updating again.

**Comment by nschonni** [comment]
If this lands before the other GitHub Actions PRs, I'll update them to filter out pushes to the dependabot branches creating builds, since they're only required on PRs
Or I can just do a separate cleanup after their all resolved

**Comment by nschonni** [comment]
@mcking65 do you want to land this one after the other GitHub Action PRs or before?

**Comment by nschonni** [comment]
@mcking65 do you want to land this one after the other GitHub Action PRs or before?

**Comment by mcking65** [comment]
@nschonni I'm not clear what is best order. I'm waiting on tests and then landing #1518 now. And, will I think do #1515 afterthat ... later in day.

**Comment by nschonni** [comment]
no problem, I've rebased #1518 since it looks like Travis got stuck

**Pull request merged**
