### PR TITLE
Initial implementation of a Hide/show widget for showing a long description of a image and faq details

### PR DESCRIPTION
**Pull request by jongund**

### CODE REVIEW

**Comment by mcking65** [comment]
@jongund,

I pushed some changes to your hide-show branch. So, please do a git pull in your hide-show branch and have a look at the log. 

Before we merge, will you please:

1. Rename the directory to "disclosure".
2. Optional: Consider eliminating the 3rd-level directory with the "-1" suffix. Do you really think we will have multiple examples? Even if we do, it seems simpler to put multiple html files in the disclosure directory.
3. Fetch the latest from master and rebase your feature branch.

Commands to rebase assuming you have git bash open to your fork of w3c/aria-practices:

Git checkout master
git pull
git checkout hide-show
git rebase master

Many thanks!!

**Comment by jongund** [comment]
Matt,

Is ‘disclosure” an industry term for hide/show functionality.

I know what you mean, but I just want it clear to people who are new and have limited time to make sure they can find things in the practices easily.

I prefer a section labelled “Hide/Show Button”.

I would like to have several examples including images, more information and help messages.  This is a common widget and we should have many examples to show all the variations.   Many people find the example and then may look at the guidance.

Jon

**Comment by jongund** [comment]
Matt,

I made the updates and added a FAQ example for review.

I renamed files to make the associations easier to understand.

Created a new pull request.

Jon

**Comment by mcking65** [comment]
@jongund, I completed changes and pushed to your fork. 
I will merge now.

**Pull request merged**
