### PR TITLE
Combobox examples with list popups: Fix missing closing LI in accessibility features section

### PR DESCRIPTION
**Pull request by nschonni**
Addresses the current CI failure on main branch

### CODE REVIEW

**Comment by nschonni** [comment]
@mcking65 @jongund this should fix the current unrelated failures in the other PRs

**Review by mcking65 — APPROVED** [review]
Thank you @nschonni!

**Comment by nschonni** [comment]
@mcking65 the regression failure is an unrelated one around the date pickers again, but this should be OK to land

**Comment by mcking65** [comment]
@howard-e 

Not related to this PR, we have a new failing test:

>not ok 21 - combobox/combobox-datepicker.html [data-test-id="month-year-button-space-return"]: ENTER on previous year or month

**Pull request merged**
