### PR TITLE
Source patterns and practices pages in APG (Issue #2702)

### PR DESCRIPTION
**Pull request by alflennik**
Sources the patterns and practices pages and all content on them, including images, from the aria-practices repo instead of bolted on later within the wai-aria-practices repo. 

The change can be previewed here: https://deploy-preview-280--aria-practices.netlify.app/

Since this PR includes changes to the structure of the content the automatic preview link generated below is not expected to work.

See https://github.com/w3c/aria-practices/issues/2702 for more information.

This PR should be merged before https://github.com/w3c/wai-aria-practices/pull/280.
___
WAI Preview Link [failed to build](https://github.com/w3c/wai-aria-practices/runs/19187018567?check_suite_focus=true) on 'Update site files' step. _(Last tried on Thu, 30 Nov 2023 16:14:25 GMT)._

### CODE REVIEW

**Comment by mcking65** [comment]
@alflennik 

I'm not able to review because the files tab won't load. When there are a lot of changed files, there is something that makes Chrome and any screen reader freeze. I need to find another way to review.

However, I was expecting this pull request would only change 2 html files and possibly add some images. So, I am surprised to see 124 changed files. The only html files that I thought would be touched are patterns.html and practices.html. What are the other files changed by this PR?

Also, the preview is failing.

**Comment by mcking65** [comment]
@alflennik 

OK, as is often the case, there is far more to our content than I realized. From the cmd line, I got the list of changed files. I see 31 changes are the addition of image files. I looked at diffs for a few of the HTML files locally, and see there is far more use of images than I knew about.

It's a happy thing to learn about all the work people have done to make a good visual presentation. I'm also now even more glad that we are moving control of that visual presentation into the content repo. Everything looks on track here, but it will take a bit of time for me to review.

It is important we get the preview working again. We are going to need others to review the preview and ensure the visual presentation is consistent with production.

**Comment by alflennik** [comment]
@mcking65 Sorry I forgot to add the preview link! I added it to the PR description. I should have remembered to do that when I opened the PR, it would seem I'm still getting in the swing of things after a while away from this repo. 

Also, thanks for the kind comments!

**Review by jongund — APPROVED** [review]
Reviewed Accordion through meter patterns and the patterns page, I didn't find any problems with images or content.

**Comment by mcking65** [comment]
Thank you, thank you @jongund and @ariellalgilmore!!!

**Comment by a11ydoer** [comment]
@mcking65 I reviewed and compared the practice page with the PR version. I didnot find any discrepancies.

**Review by mcking65 — APPROVED** [review]
@alflennik 

Looking at the HTML, this looks really good to me. It fully resolves the issue. Based on the feedback from @jongund, @a11ydoer, and @ariellalgilmore, it seems that the presentation also remains as expected.

Thank you!!!

If @howard-e also agrees this is ready to merge, I will mergeMonday morning so we can get this into production this week.

**Review by howard-e — APPROVED** [review]
Looks good to me! Shared my actual PR feedback in the [build repo](https://github.com/w3c/wai-aria-practices/pull/280#pullrequestreview-1775212889).

**Comment by alflennik** [comment]
Thanks all!

**Pull request merged**
