### PR TITLE
Update menubar navigation example

### PR DESCRIPTION
**Pull request by jongund**
Update to menubar navigation exmaple is ready for review:

[Preview Link](https://raw.githack.com/w3c/aria-practices/update-menubar-nav/examples/menubar/menubar-navigation.html)

Changes:
* Added landmark regions to mimic a website look and feel
*  When links selected the content area is updated and the focus moves to the H1 element, previous version went to a dummy link
* Updated code to use coding practices

### CODE REVIEW

**Comment by jongund** [comment]
@mcking65 
@spectranaut 
I am getting eslinting errors on many files (e.g. "error  Use the global form of 'use strict'  strict") that are not part of this pull request, what should I do?
I have merged from master, but still getting the errors.

**Comment by nschonni** [comment]
@jongund it looks like when you merged in your branch, you stripped off a bunch of the `use strict` statements in unrelated files

**Comment by nschonni** [comment]
@jongund was able to reproduce your issues locally, but I was able to resolve the issue by rebasing. You could try this locally to see if if helps, but might put you in a "bad" state if you're not familiar with git:
1. `git pull --rebase upstream master`. upstream might not be the right remove for you since this branch is in the same repo
1. Resolve the git conflicts through the rebase
1. `git rebase -i HEAD~16` and squashed down all the commits using "fixup" choice for all but the first commit
1. I copied the end `test/tests/menubar_menubar-navigation.js` from here since my rebase left it in a bad state

You'd need to force push back the branch at the end.

I can submit my end branch if you want, and just let push your updates to it if you want

**Comment by jongund** [comment]
messed up synchronization of files with master, so going to start over, by deleting this branch and creating a new branch  for menubar navigation updates.

**Pull request closed without merging**
