### PR TITLE
Run CI on bocoup branch

### PR DESCRIPTION
**Pull request by spectranaut**
CI presently doesn't run tests on PRs to bocoup branch

### CODE REVIEW

**Comment by spectranaut** [comment]
Hi @mcking65 -- can you merge this to master, so I can see the our tests running on the bocoup branch when I open a PR?

**Comment by nschonni** [comment]
#445 will also enable this :wink:

**Comment by nschonni** [comment]
This may actually cause that branch to get published with the current setup

**Comment by spectranaut** [comment]
Oh wow - @nschonni nice catch and also thanks for #445 :)

**Pull request closed without merging**
