### PR TITLE
Infrastructure: Add newline at EOF when generating example index

### PR DESCRIPTION
**Pull request by nschonni**

### CODE REVIEW

**Comment by nschonni** [comment]
@mcking65 this should fix the generation job issue

**Comment by nschonni** [comment]
@mcking65 this will revert your change from #1670 because manually editing the index file with an editor with EditorConfig will add the newline.

**Review by spectranaut — APPROVED** [review]
Thanks for this!

**Comment by mcking65** [comment]
@nschonni 
I never touched the index file with an editor. I think the package we have that auto-enforces the editorconfig on commit must have done that.

**Comment by nschonni** [comment]
@mcking65 you fix definitely works and unblocked the failing CI. This way of updating the template script and adding back the trailing newline just allows people to manually edit the file in addition to using the generation script, depending on their setup.

**Review by mcking65 — APPROVED** [review]
Thank you @nschonni.

**Pull request merged**
