### PR TITLE
Move alert-dialog example into alert-dialog pattern (Issue 2418 Task)

### PR DESCRIPTION
**Pull request by alflennik**
Extracts the alert-dialog example from its current position under the dialog-modal pattern directory to the alert-dialog pattern directory. I simplified the source code and removed any dependencies on code in the dialog-modal directory.

Resolves Issue https://github.com/w3c/aria-practices/issues/2488.

See Issue #2418 for more context. Note that the current PR base is https://github.com/w3c/aria-practices/pull/2499. Once that PR is merged the base of this PR should be changed to https://github.com/w3c/aria-practices/pull/2417.

### CODE REVIEW

**Review by mcking65 — CHANGES_REQUESTED** [review]
I did a quick test of the example and found that the js is not behaving the same. For instance, focus is not properly trapped. There must be some methods in the dialog.js that were not copied over or replicated.

I am rather concerned that the regression testing did not capture this. We should open an issue to add regression tests that thoroughly test tab key behavior and initial focus in the dialog examples ... or fix them if the tests are there but not complete.

**Comment by alflennik** [comment]
Thanks for the feedback @mcking65, the reason the regression tests did not catch the issue is that there was no regression test for this example. I wrote a regression test and fixed several issues including the one you pointed out where it's possible to tab out of the dialog. Thanks for your patience as I figure out how the examples are authored!

**Comment by mcking65** [comment]
@alflennik, this is working now, and thank you for the additional tests!!!

Unfortunately, since I merged #2499, looks like we have a pile of conflicts.

**Comment by alflennik** [comment]
Great to hear it's working!

**Pull request merged**
